In [2]:
import pandas as pd

# display columns without truncation
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

# display rows without truncation
pd.set_option("display.max_rows", None)
pd.set_option("display.expand_frame_repr", False)

In [6]:
roles_only = pd.read_csv(r"D:\commo\code\role_assignment\assigned_only_roles.csv")
# standardized pillars
node_list1 = pd.read_csv(r"D:\commo\code\cleaned_pillars\standardized_pillar1.csv")
node_list2 = pd.read_csv(r"D:\commo\code\cleaned_pillars\standardized_pillar2.csv")
node_list3 = pd.read_csv(r"D:\commo\code\cleaned_pillars\standardized_pillar3.csv")

In [ ]:
"""
The node lists for kumu contain columns such as (Id), Label, Type, Description, (Tags), and other cols according to each entity type. 
In the edge list, it contains columns such as From, To, Direction, Type, Strength, and Description.
"""

In [7]:
# re order the columns in node_list1

node_list1.rename(columns={'Company Name': 'Label'}, inplace=True)
# move the label col to index 0
# Get the name of the label column at index 0
label_col = node_list1.columns[1]
# Pop the column and insert it at index 0, run one time
node_list1.insert(0, 'Label', node_list1.pop(label_col))

# insert the Type col, which is the role(s)
role_map = roles_only.set_index("name")["role(s)"]
node_list1.insert(1, "Type", pd.NA) # run one time
node_list1["Type"] = node_list1["Label"].map(role_map) 

# move the Notes to index 2 as description
desc_col = node_list1.columns[-1]
node_list1.insert(2, 'Description', node_list1.pop(desc_col))

# move the apac office address to the end
add_col = node_list1.columns[8]
node_list1["APAC offices"] = node_list1.pop(add_col)


# replace commas with |
def comma_to_tag(cell):
    if pd.isna(cell) or not isinstance(cell, str) or not cell.strip():
        return None 
    return cell.replace(",", " |")
node_list1["Commodity Type"] = node_list1["Commodity Type"].apply(comma_to_tag)
node_list1["Commodity Focus"] = node_list1["Commodity Focus"].apply(comma_to_tag)
node_list1["HQ Country"] = node_list1["HQ Country"].apply(comma_to_tag)
node_list1["Exchange"] = node_list1["Exchange"].apply(comma_to_tag)

# replace tier 3 with 1, and tier 1 with 3 so that kumu knows bigger number = bigger companies
node_list1["Tier"] = node_list1["Tier"].replace({1: 3, 3: 1})
node_list1
# save node_list1

                                                Label            Type                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Description  Tier                      Commodity Type                                                                                                                                                                                                                      Commodity Focus                                                                                    Legal Name / ACRA UEN               HQ Country                                                                                                             Estimated Revenue                                                                Headcount (Global)                                                                                                                                                                                                                                                                                      Trade Volume (Est.)                             Ownership Structure                                                                           Exchange                                                                                                                                                                                                           APAC offices
0                                     trafigura group  trader, lender                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Latest acquisition (after Sep 2025): Greenergy that is owned by trafigura, acquired France's Armorine Group (trafigura 2025 annual report)     3                    multi (>2 types)                                                                                                                                                                     oil | petroleum | natural gas | LNG | metals | soft/agricultural                                                       TRAFIGURA GROUP PTE. LTD. / 201017488D (recordowl)                Singapore                                                                          Trafigura Group: 240.3 USD bn FY2025 (trafigura.com)                                                                   5011 (linkedin)                                                                                                                                                                                                                                            approx. 462 million metric tons (2025 annual report + claude)                                         private                                                                               None                                                                                                                            10 Collyer Quay, #29-01/05, Ocean Financial Centre, Singapore 049315, Singapore (recordowl)
1                                          vitol asia          trader                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Its largest operations are in Geneva, Houston, London and Singapore. (world economic forum)     3                    multi (>2 types)                                                                                                                       crude oil | petroleum | LNG | natural gas | biogas/bioLNG | thermal coal | metcoke | metals | power | plastics                                                             VITOL ASIA PTE LTD. / 199001917Z (recordowl)              Switzerland                                                                             Turnover of $343 billion FY2025 (company website)                                                                   1990 (linkedin)                                                                                                                                                                                                                total energy trade volume: 605 million tonnes of oil equivalent (mTOE ) (company website)                                         private                                                                               None                                                                                                                                                            128 BEACH ROAD #28-01 GUOCO MIDTOWN OFFICE SINGAPORE 189773
2                                   mercuria holdings          others                                                                                                                                                                                                                                                                                                                                                                                  Mercuria Holdings (Singapore) Pte. Ltd. is a global commodity trader connecting essential resources to energy markets, operating globally and at scale. The company operates in over 50 countries across 5 continents and has a main trading hub located in Geneva, Switzerland. (recordowl)     3                    multi (>2 types)                                                                                                                                                                                                  energy | metals | soft/agricultural                                         MERCURIA HOLDINGS (SINGAPORE) PTE. LTD. / 201808173Z (recordowl)              Switzerland                                                                                                    $618.7 Million (zoom.info)                                                                   1380 (linkedin)                                                                                                                                                                                                                                            6M+ barrels of oil equivalent (BOE) per day (company website)                                         private                                                                               None                                                                                                                                           12 Marina View, #26-01, Asia Square Tower 2, Singapore 018961 (mercuria.com)
3                                    gunvor singapore          trader                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            one of the world's largest independent commodities trading houses by turnover. It has trading offices in Geneva, Singapore, the Bahamas and Dubai.     3                              energy                                                                                                                                               crude oil | refined petroleum products | natural gas | LNG | biofuels | power | carbon                                                   GUNVOR SINGAPORE PTE. LTD. / 200606959K (acra bizfile)              Switzerland                                                                                             US $144 billion (company website)                                                                   1035 (linkedin)                                                                                                                                                                                                                                                                         253 million MT (company website)                                         private                                                                               None                                                                                                                                         128 Beach Road, #29-01, Guoco Midtown Office, Singapore 189773 (recordowl.com)
4                          louis dreyfus company asia          trader                                                                                                                                                                LDC is purely agricultural, no energy commodity trading, heavily weighted towards grains & oilseeds, Profitability declined slightly in 2025 vs. 2024 (EBITDA -2.8%, Net Income -10%) despite higher revenues, due to tariff headwinds, geopolitical uncertainty, and higher finance costs, Aggressive capex cycle: capital expenditure nearly doubled to US$2.0 billion in 2025 (from US$1.0 billion in 2024), reflecting major processing and logistics expansion (2025.12 LDC - Integrated Report + claude)     3                   soft/agricultural                                                                                                                                                                           grains | oilseeds | coffee | cotton | sugar | rice | juice                                         LOUIS DREYFUS COMPANY ASIA PTE. LTD. / 199306551Z (acra bizfile)              Netherlands                                                                Net Sales: US$ 53.2bn FY2025 (2025.12 LDC - Integrated Report)                                                                 13,359 (linkedin)                                                                                                                                                                                    ~100 million tonnes of products shipped annually, with volumes up 10.6% YoY in 2025 (2025.12 LDC - Integrated Report)                                         private                                                                               None                                                                                                                              12 MARINA BOULEVARD #33-03 MARINA BAY FINANCIAL CENTRE SINGAPORE 018982 (company website)
5                                wilmar international          trader  Wilmar is Asia's largest agribusiness group, founded in 1991 and headquartered in Singapore. The Group's business activities include oil palm cultivation, oilseed crushing, edible oils refining, flour and rice milling, sugar milling and refining, manufacturing of consumer products, ready-to-eat meals, central kitchen products, specialty fats, oleochemicals, biodiesel and fertilisers as well as food park operations. FY2025 faced misconduct allegations involving a subsidiary and a state-owned enterprise but the company categorically denied all allegations and stated it will defend its position through legal channels. (annual report 2025 + claude)     3                   soft/agricultural                                                                                                                                                                                                  palm oil | sugar | grain | oilseeds                                                    WILMAR INTERNATIONAL LIMITED / 199904785Z (recordowl)                Singapore                                                                                                US$70.42B (Annual Report 2025)                                                                  7,723 (linkedin)                                                                                                                                                                                                                                                                   ~105.8 million MT (Annual report 2025)                                          listed                                                             Singapore Exchange SGX                                                                                                                                                          28 Biopolis Road, Singapore 138568 (wilmar-international.com)
6                                          olam group  trader, lender                                    Olam divides into 3: olam food ingredients (ofi), olam agri (discontinuing as being sold to SALIC), remaining olam group. Its immediate parent is Temasek Capital (Private) Limited.Olam is undergoing a major Re-organisation Plan — it is divesting Olam Agri (the largest segment by volume and revenue) to SALIC and intends to distribute net proceeds progressively to shareholders, leaving ofi as the primary remaining operating business. Olam is exclusively agricultural.Co-Founder and Group CEO Sunny George Verghese is stepping down as Executive Director and Group CEO following the 2026 AGM. (olam annual report 2025)     3                   soft/agricultural                                                                                                                                                                                             cocoa | coffee | cottons | nuts | spices                                                          OLAM GROUP LIMITED / 202180000W (olamgroup.com)                Singapore                                    Total Sales Revenue: S$66,997.3 million (~S$67.0 billion) FY2025 (olam annual report 2025)                                                                   8766 (linkedin)                                                                                                                                                                                                                            58,091,900 metric tonnes (58.1 million MT) globally (olam annual report 2025)                                          listed                                                             Singapore Exchange SGX                                                                                                                                        7 Straits View, #20-01, Marina One East Tower, Singapore 018936 (olamgroup.com)
7                       cofco international singapore          trader                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           19 March 2026: COFCO International and Standard Chartered close USD 435 Million sustainability-linked loan (cofcointernational.com)     3                   soft/agricultural                                                                                                                                                                                                   grains | oilseeds | sugar | cotton                                         COFCO INTERNATIONAL SINGAPORE PTE. LTD. / 200101811W (recordowl)                    China                                                        USD 54.0 bn revenue FY2024 (cofcointernational.com 2024 annual review)                              ~11,000  (cofcointernational.com 2024 annual review)                                                                                                                                                                                           approx. 130 million metric tons of agri-commodities traded in 2024 (cofcointernational.com 2024 annual review)                                     state-owned                                                                               None                                                                                                                                    150 Beach Rd, #23-01/08 The Gateway West\nSingapore 189720 (cofcointernational.com)
8                       cargill asia pacific holdings          trader                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Latest acquisition (11 august 2025): Cargill opens new retail feed facility in Granger, Washington (cargill.com)     3                    multi (>2 types)                                                                                                                                                                                                  grains | oilseeds | metals | energy                                        CARGILL ASIA PACIFIC HOLDINGS PTE. LTD. / 200401312G  (recordowl)                      USA                                                                      USD 177.0 bn revenue FY2024 (Cargill 2024 annual report)                                            ~160,000  (Cargill 2024 annual report)                                                                                                                                                                           approx. 200 million metric tons equivalent of agricultural and energy commodities handled in 2024 (Cargill 2024 annual report)                                         private                                                                               None                                                                                                                                                 138 Market Street, #17-01, CapitaGreen, Singapore 048946 (cargill.com)

In [ ]:
# re order the columns in node_list2

# rename the firm name as label
node_list2.rename(columns={'Firm Name': 'Label'}, inplace=True)

# insert the Type col, which is the role(s)
role_map = roles_only.set_index("name")["role(s)"]
node_list2.insert(1, "Type", pd.NA)  # run one time
node_list2["Type"] = node_list2["Label"].map(role_map)

# rename the Type (intl/local)
node_list2.rename(columns={'Type (Intl / Local)': 'Scope'}, inplace=True)


# move the notable cases + notes to description col at index 2
col1 = "Notable Cases / Disputes"
col2 = "Notes"
def build_description(row):
    val1 = row[col1] if isinstance(row[col1], str) and row[col1].strip() else "N/A"
    val2 = row[col2] if isinstance(row[col2], str) and row[col2].strip() else "N/A"
    return f"{col1}: {val1}\n\n{col2}: {val2}"
node_list2["Description"] = node_list2.apply(build_description, axis=1)
node_list2.insert(2, "Description", node_list2.pop("Description"))
# drop the last 2 columns
node_list2 = node_list2.drop(columns=["Notable Cases / Disputes", "Notes"])

# replace commas with |
def comma_to_tag(cell):
    if pd.isna(cell) or not isinstance(cell, str) or not cell.strip():
        return None
    return cell.replace(",", " |")
node_list2['Practice Areas'] = node_list2['Practice Areas'].apply(comma_to_tag)

node_list2
# save node_list2

                           Label    Type                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Description            Scope                                                                                                                         Office Location(s) in APAC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Practice Areas                                                                                                                                               Known Client Base
0                     reed smith  lawyer                                                                                                                                                                                                                                                                            Notable Cases / Disputes: RTI Ltd v MUR Shipping BV [2024] UKSC 18, Sharp Corp Ltd v Viterra BV [2024] UKSC 14, The Aquafreedom [2024] EWHC 255 (Comm), The Ever Given – SMIT Salvage BV and Others v Luster Maritime SA [2024] EWCA Civ 260, Maersk Guiné-Bissau v Almar-Hum Bubacar Baldé [2024] EWHC 993 (Comm) (reedsmith.com)\n\nNotes: website: https://www.reedsmith.com/    International                                                                   10 Collyer Quay, #18-01 Ocean Financial Centre, Singapore 049315 (Reedsmith.Com)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Dispute Resolution & Litigation | Regulatory & Compliance                         china merchants energy shipping holding singapore, sinopec, trafigura maritime logistics, uniper global commodities se singapore branch
1      holman fenwick willan hfw  lawyer                                                                                                                                                                                                                                                                                                                                                Notable Cases / Disputes: The "Rena" Grounding, OW Bunker Bankruptcy, The "Prestige" Oil Spill, The "Ocean Victory" Case (https://www.studocu.com/en-gb/messages/question/5472340/what-are-some-famous-cases-that-were-advised-by-hfw-and-how-were-they-influential)\n\nNotes: website: https://www.hfw.com/    International                                                                                    30 Raffles Place, #24-01, Bni Tower, Singapore 048622 (Hfw.Com)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Corporate & M&A | Banking & Finance | Dispute Resolution & Litigation | Regulatory & Compliance                                                               bgn energy, equatorial marine fuel management services, mitsui & co energy trading singapore mets
2                     clyde & co  lawyer                                                                                                                                                                                                    Notable Cases / Disputes: The 'Brillante Virtuoso' Case, Precedent setting FOSFA sale of goods arbitration (switzerland), Appealing the Refined Sugar Associations Arbitration Award (UK), Collision of VLCC "ALEXANDRA 1" and "EVER SMART" (UK), Penglai 19-3 Oil Field Pollution (China/USA),  COSCO BUSAN Allision with San Francisco-Oakland Bay Bridge (USA), Agarwal Coal High Court Appeal (UK) (claude + clydeco.com + perplexity)\n\nNotes: N/A    International                                                    12 Marina Boulevard, #30-03 Marina Bay Financial Centre Tower 3, Singapore 018982 (Clydeco.Com)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Corporate & M&A | Banking & Finance | Dispute Resolution & Litigation | Regulatory & Compliance | Real Estate & Construction | Employment & Labor                                                                                                                              ed&f man capital markets singapore
3             stephenson harwood  lawyer                                                                                                                                                                                                                                                                       Notable Cases / Disputes: former Yukos Oil Company shareholders v The Russian Federation, Trafigura Pte Ltd & Anor v Prateek Gupta & Ors [2026] EWHC 159 (Comm), SLB and others v PAK and others [2026] EWHC 449 (Comm), GAIL (India) Limited v SEFE Marketing & Trading Singapore Pte Limited, Narciso v Nash (ARB 009/2024) (google AI + google  & news + claude AI )\n\nNotes: N/A    International  Stephenson Harwood (Singapore) Alliance, 8 Marina Boulevard #29-01, Marina Bay Financial Centre Tower 1, Singapore 018981 (Stephensonharwood.Com)                                                                                                                                                                                                                                                                             Corporate & M&A | Banking & Finance | Dispute Resolution & Litigation | Fraud | Investigations & White Collar | Regulatory & Compliance | Real Estate & Construction | Employment & Labor | Intellectual Property | Shipping & Maritime | International Trade & Commodities | Energy & Infrastructure | Private Wealth & Estate Planning | Technology | Data & Cybersecurity | Insurance                                                                                                        icici bank singapore branch, olam group, trafigura group
4       watson farley & williams  lawyer                                                                                                                                                                                                Notable Cases / Disputes: The merger between Hapag-Lloyd and the United Arab Shipping Company (UASC), WFW advises Guinea as US$24bn Simandou African mega-project closes, Niko Resources (Bangladesh) Ltd v. Bangladesh Petroleum Exploration & Production Company Limited ("Bapex") and Bangladesh Oil Gas and Mineral Corporation ("Petrobangla"), MRI Trading AG v Erdenet Mining Corp LLC (2013) (perplexity + google AI)\n\nNotes: https://www.wfw.com/    International                                                                      88 Market Street #31-05, Capitaspring, Singapore, 048948, Singapore (Wfw.Com)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Corporate & M&A | Banking & Finance | Capital Markets | Dispute Resolution & Litigation | Regulatory & Compliance | Competition & Antitrust                                                                                                    bw energy holdings, hsbc singapore entities, trafigura group
5            ince & co singapore  lawyer                                                                                                                                                                                                                                                                                                     Notable Cases / Disputes: Global Coal Ltd v London Commodity Brokers (vlex.couk),Statoil ASA v Louis Dreyfus Energy Services LP (The Harriette N)(ipsaloquitur.com ), Priyanka Shipping Limited v Glory Bulk Carriers Pte Ltd [2019] EWHC 2804 (Comm) (Gemini)\n\nNotes: Rosita Lau (Partner & Head of Shipping), Ince don't have  office in sg(gemini)    International                                                                                              5 Shenton Way, #19-01, Uic Building, Singapore 068808                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Dispute Resolution & Litigation | Shipping & Maritime | International Trade & Commodities | Energy & Infrastructure | Insurance                                                                                                        glory bulk carriers, tai chong cheang shipping singapore
6          norton rose fulbright  lawyer                                                                                                                                                                   Notable Cases / Disputes: Suez Fortune Investments Ltd v Talbot(gemini), PD Teesport Ltd v. P&O North Sea Ferries Ltd — Force Majeure / Ferry Operator Dispute (2022–2023), Carnival Corporation v. Fincantieri S.p.A — Shipbuilding Contract / Breach of Guarantee (Ongoing as of 2024–2025), Shell UK v. Greenpeace UK — FPSO Boarding Dispute (2023–2024), KfW IPEX-Bank v. World Dream Limited ("The World Dream") — Ship Mortgage Enforcement (2022–2024) (perplexity)\n\nNotes: N/A    International                                                       Norton Rose Fulbright (Asia) Llp ,9 Straits Viewmarina One West Tower#09-09 Singapore 018937                                                                                                                                                                                                                                                                                                                               Corporate & M&A | Banking & Finance | Capital Markets | Private Equity & Venture Capital | Dispute Resolution & Litigation | Restructuring & Insolvency | Fraud | Investigations & White Collar | Real Estate & Construction | Employment & Labor | Intellectual Property | Energy & Infrastructure | Private Wealth & Estate Planning                                                                                                                                      louis dreyfus company asia
7                 baker mckenzie  lawyer                                                                                                                                                                                                                                                                                                                                      Notable Cases / Disputes: Anaklia Development Consortium (ADC) and Bob Meijer v. Georgia (ICC & ICSID parallel claims), Lakatamia Shipping Co Ltd v Su & Ors,  Lehram Capital Investments Ltd v. Baker McKenzie, Anaklia Development Consortium (ADC) v. Government of Georgia (google ai)\n\nNotes: bakermckenzie.com    International                                                                        38 Beach Road #23-11 South Beach Tower Singapore 189767 (Bakermckenzie.Com)                                                                                                                                      Corporate & M&A | Banking & Finance | Capital Markets | Private Equity & Venture Capital | Funds & Investment Management | Dispute Resolution & Litigation | Restructuring & Insolvency | Fraud | Investigations & White Collar | Regulatory & Compliance | Competition & Antitrust | Real Estate & Construction | Employment & Labor | Intellectual Property | Tax | International Trade & Commodities | Energy & Infrastructure | Private Wealth & Estate Planning | Technology | Data & Cybersecurity | ESG & Sustainability                                                                                                                          shell eastern trading, shell singapore
8            squire patton boggs  lawyer                                                                                                                                                                      Notable Cases / Disputes: LG Caltex v CNPC, Triad Shipping Co v Stellar Chartering & Brokerage Inc (The "Island Archon") [1994] 2 Lloyd's Rep 227, Merit Shipping Co Inc v T.K. Boesen A/S (The "Goodpal") [2000] 1 Lloyd's Rep 638, André & Cie S.A. v Orient Shipping (Rotterdam) B.V. (The "Laconian Confidence") [1997] 1 Lloyd's Rep 139, AIC Ltd v ITS Testing Services (UK) Ltd (The "Kriti Palm") [2006] EWCA Civ 1601 (squirepattonboggs.com)\n\nNotes: squirepattonboggs.com    International                                                      1 Marina Boulevard, #21-01 One Marina Boulevard, Singapore 018989 (Www.Squirepattonboggs.Com)                                                                                                                                                                                                                                                                                                                                                   Corporate & M&A | Banking & Finance | Private Equity & Venture Capital | International Arbitration | Real Estate & Construction | Shipping & Maritime | International Trade & Commodities | Energy & Infrastructure | Private Wealth & Estate Planning | Technology | Data & Cybersecurity | Hospitality & Leisure                                                                                                                                                             NaN
9                 hill dickinson  lawyer                                                                                                                                                                                                                                                                                                                Notable Cases / Disputes: SY Roro 1 Pte Ltd and another v Onorato Armatori S.R.L. and others [2024] EWHC 611 (Comm) (google AI), Trafigura PTE Ltd & Anor v Gupta & Ors [2026] EWHC 159 (Comm) (hilldickinson.com/our-view/articles/commodity-trader-successful-in-fraudulent-nickel-trade-claims/)\n\nNotes: https://www.hilldickinson.com/    International                                                        3 Anson Road, Springleaf Tower, 24-03, Singapore, 079909, Sg ( Hill Dickinson Llp Linkedin)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Corporate & M&A | Banking & Finance | Dispute Resolution & Litigation | Regulatory & Compliance | Real Estate & Construction | Private Wealth & Estate Planning                                                                                                                                                 trafigura group
10               mayer brown llp  lawyer                                                                                                                                                                                                                                                                                                                                      Notable Cases / Disputes: Clearlake Shipping Pte Ltd v. Guvnor Shipping & Others, Aabar Holdings v. Glencore plc, The "Reluctant Ship Owner" Mortgages Enforcement Action, In re: Singamas and Container Cartel Litigation, In re: Glencore PLC SFO Investigation (perplexity)\n\nNotes: https://www.mayerbrown.com/en    International                                                        6 Battery Road, #10-01, Singapore 049909 (Https://Www.Mayerbrown.Com/En/About-Us/Locations)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Corporate & M&A | Banking & Finance | Dispute Resolution & Litigation                                                                                                                                                             NaN

In [23]:
# re order the columns in node_list3
node_list3.rename(columns={'Institution Name': 'Label', 'Category':'Financier Type'}, inplace=True)

# insert the Type col, which is the role(s) at index 1
role_map = roles_only.set_index("name")["role(s)"]
node_list3.insert(1, "Type", pd.NA)  # run one time
node_list3["Type"] = node_list3["Label"].map(role_map)

# move the Notes to index 2 as description
node_list3.insert(2, "Description", node_list3.pop('Notes'))


# replace commas with |
def comma_to_tag(cell):
    if pd.isna(cell) or not isinstance(cell, str) or not cell.strip():
        return None
    return cell.replace(",", " |")
node_list3["Commodity Type"] = node_list3["Commodity Type"].apply(comma_to_tag)
node_list3
# save node_list3

                                                     Label            Type                                                                                                                                                                                                                                                                                                                     Description         Financier Type                                             Commodity Type                                                                                                                                                                                                          Geographic Reach                                                                                                                                                                Known Clients
0                                                      ing          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                                                                      EMEA, APAC, Americas                                                                                                                         glencore, gunvor group, trafigura group, vitol group
1                                         societe generale          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                                      Primary base , North America, APAC, emerging markets                                                                                                                                                                          NaN
2                                              bnp paribas          lender                                                                                                                                                                                sep 2020: BNP Paribas Suisse discontinued financing commodity trading and announced restructuring affecting 120 employees in Geneva (perplexity)       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                 Europe , Americas , APAC, Africa. Global network spans over 100 countries                                                                                                                                                                          NaN
3                                                 rabobank          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                       EU, Americas, Asia, Africa, ~38 countries across Europe, North America, South America, Asia, Australia, New Zealand                                                                                                                                                                          NaN
4                                       standard chartered          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank        energy | hard/metals | soft/agricultural | emerging                                                                                                                                               Asia-Pacific , China & India , Africa , Middle East , Latin America, UK, US                                                                                                                    glencore, marubeni corporation, seatrium, trafigura group
5                                                 dbs bank          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                      Southeast Asia , Greater China , South Asia , Australia, Europe , Africa, Middle East, Latin America                                                                              agrocorp international, louis dreyfus company, rio tinto, trafigura group, wilmar international
6                 oversea-chinese banking corporation ocbc          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                             Southeast Asia , Greater China , Asia , Europe, Australia, US                                                                                                                                                                          NaN
7                                 united overseas bank uob          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                         Australia, brunei, canada, mainland china, france, hong kong, india, indonesia, japan, malaysia, myanmar, philippines, singapore, south korea, taiwan, thailand, uk, usa, vietnam                                                                                         barramundi group, cargill, musim mas holdings, sinar mas group, wilmar international
8                                                     mufg          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                               ~50 countries, ~3,000 locations globally; strong in Asia Pacific , EMEA , and North America                                                                                     bunge, cofco international, gunvor group, mercuria, six one commodities, trafigura group
9                                                     smbc          lender                                                                                                                                                                                                                                                                 SMBC remains fully active in commodity trade finance as of 2026       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                            Japan , SEA, China, South Asia, Middle East, Africa, EU, North America, Latin America, Oceania  cofco international, gunvor group, louis dreyfus company, mercuria energy group, olam food ingredients, rio tinto, trafigura group, vale, vitol group, wilmar international
10                                         credit agricole          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                            Switzerland/Western EU , Americas, APAC, SEA, Middle East, Greater China, Korea, Japan, Africa                                                                                       cofco international, gunvor group, mercuria energy group, trafigura group, vitol group
11                                                    hsbc          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                       APAC, North America, Latin America, EMEA, MENAT, Sub-saharan africa                                                                                                     glencore, gunvor group, olam agri holdings, sinar mas group, vitol group
12                                                 natixis          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                                        France / EU , Americas, APAC, Middle East / Africa                                                                                                              cofco international, gunvor group, trafigura group, vitol group
13                          bank of china singapore branch          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                                                     energy                                                                                                                                                                                                               APAC, ASEAN                                                                                                                                                             unipec singapore
14                china construction bank singapore branch          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                                                     others                                                                                                                                                                              Singapore, China, South Asia, Southeast Asia                                                                                                                                                              trafigura group
15                                   icbc singapore branch          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                                       energy | hard/metals                                                                                                                                                                                            Global with Asia-Pacific focus                                                                                                                                                              trafigura group
16             agricultural bank of china singapore branch          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                                       energy | hard/metals                                                                                                                                                                                                                   SG, SEA                                                                                                                                                          trafigura beheer bv
17  shanghai pudong development bank spdb singapore branch          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                                                     others                                                                                                                                                                                                                   SG, SEA                                                                                                                                                                          NaN
18                              mufg bank singapore branch          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                                                        Global with emerging markets focus                                                                                                                                                      mercuria energy trading
19                         macquarie bank singapore branch          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                                       energy | hard/metals                                                                                                                                                                                                                      ASIA                                                                                                                                                                          NaN
20     commonwealth bank of australia cba singapore branch          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                                                   emerging                                                                                                                                                                                                                      APAC                                                                                                                                                                          NaN
21                               anz bank singapore branch          lender                                                                                                                                                                                                                                                                                                                             NaN       Traditional Bank                   energy | hard/metals | soft/agricultural                                                                                                                                                                                                                    global                                                                                                                                                                          NaN

In [24]:
# In the edge list, it contains columns such as From, To, Direction, Type
edge_list = pd.DataFrame(columns=['From', 'To', 'Direction', 'Type'])

# note the node_list2 Label (edge type: counsels_for) Known Client Base
# explode node_list2 known client base into individual rows
import re
def split_names(row):
    if not isinstance(row, str) or not row.strip(): # if not row.strip() = True > not real content
        return []
    parts = re.split(r',\s*(?![^()]*\))', row)
    return [p.strip() for p in parts]
node_list2_exploded = node_list2[['Label', 'Known Client Base']].copy()
node_list2_exploded['Known Client Base'] = node_list2_exploded['Known Client Base'].apply(split_names) # each client row has list of comma-separated str
node_list2_exploded = node_list2_exploded.explode('Known Client Base').reset_index(drop=True) # each row has one client but same law firm
# change Label to 'From', known client base to 'to'
node_list2_exploded.rename(columns={'Label': 'From', 'Known Client Base': 'To'}, inplace=True)
# add Direction column and edge type column
node_list2_exploded["Direction"] = "directed"
node_list2_exploded['Type'] = 'counsels_for'
# node_list2_exploded is ready for concat

# note the node_list3 Label (edge type: lends_to) Known Clients
# explode node_list3 known clients into individual rows
node_list3_exploded = node_list3[['Label', 'Known Clients']].copy()
node_list3_exploded['Known Clients'] = node_list3_exploded['Known Clients'].apply(split_names)
node_list3_exploded = node_list3_exploded.explode('Known Clients').reset_index(drop=True) #before reset_index, the exploded rows still have their original row index
# rename Label to from, Known Clients to to
node_list3_exploded.rename(columns={'Label':'From', 'Known Clients':'To'}, inplace=True)
node_list3_exploded['Direction'] = 'directed'
node_list3_exploded['Type'] = 'lends_to'
# node_list3_exploded is ready for concat

# node_list1 lends_to? owns?
node_list1_edges = pd.DataFrame(
    [
        {"From": "trafigura beheer bv", "To": "trafigura group", 'Direction':'directed', 'Type':'owns'},
        {"From": "trafigura group", "To": "trafigura carbon trading", 'Direction':'directed', 'Type':'owns'},
        {"From": "trafigura group", "To": "trafigura maritime logistics", 'Direction':'directed', 'Type':'owns'},
        {"From": "vitol group", "To": "vitol asia", 'Direction':'directed', 'Type':'owns'},
        {"From": "mercuria energy group", "To": "mercuria energy trading", 'Direction':'directed', 'Type':'owns'},
        {"From": "mercuria energy group", "To": "mercuria holdings", 'Direction':'directed', 'Type':'owns'},
        {"From": "gunvor group", "To": "gunvor singapore", 'Direction':'directed', 'Type':'owns'},
        {"From": "olam group", "To": "olam food ingredients", 'Direction':'directed', 'Type':'owns'},
        {"From": "olam group", "To": "olam agri holdings", 'Direction':'directed', 'Type':'owns'},
        {"From": "louis dreyfus company", "To": "louis dreyfus company asia", 'Direction':'directed', 'Type':'owns'},
        {"From": "cofco international", "To": "cofco international singapore", 'Direction':'directed', 'Type':'owns'},
        {"From": "glencore", "To": "glencore singapore", 'Direction':'directed', 'Type':'owns'},
        {"From": "mitsui & co", "To": "mitsui & co energy trading singapore (mets)", 'Direction':'directed', 'Type':'owns'},
        {"From": "shell singapore", "To": "shell eastern trading", 'Direction':'directed', 'Type':'owns'},
        {"From": "sinopec", "To": "unipec singapore", 'Direction':'directed', 'Type':'owns'},
        {"From": "sinopec", "To": "sinopec international", 'Direction':'directed', 'Type':'owns'},
        {"From": "sinopec", "To": "sinopec international singapore", 'Direction':'directed', 'Type':'owns'},
        {"From": "sinopec", "To": "sinopec fuel oil", 'Direction':'directed', 'Type':'owns'},
        {"From": "petrochina international", "To": "petrochina international singapore", 'Direction':'directed', 'Type':'owns'},
        {"From": "sinar mas group", "To": "golden agri international", 'Direction':'directed', 'Type':'owns'},
        {"From": "standard chartered", "To": "standard chartered bank singapore scb", 'Direction':'directed', 'Type':'owns'},
        {"From": "ed&f man capital", "To": "ed&f man capital markets singapore", 'Direction':'directed', 'Type':'owns'},
        {"From": "wilmar international", "To": "wilmar sugar", 'Direction':'directed', 'Type':'owns'},
        {"From": "cargill", "To": "cargill asia pacific holdings", 'Direction':'directed', 'Type':'owns'},
        {"From": "bunge", "To": "bunge asia", 'Direction':'directed', 'Type':'owns'},
        {"From": "trafigura group", "To": "lex oil", 'Direction':'directed', 'Type':'lends_to'},
        {"From": "trafigura group", "To": "develop global", 'Direction':'directed', 'Type':'lends_to'},
        {"From": "trafigura group", "To": "woodlawn mine holdings", 'Direction':'directed', 'Type':'lends_to'},
        {"From": "trafigura group", "To": "tarago operations", 'Direction':'directed', 'Type':'lends_to'},
        {"From": "gunvor group", "To": "amaroq", 'Direction':'directed', 'Type':'lends_to'},
        {"From": "vitol group", "To": "uganda national oil unoc", 'Direction':'directed', 'Type':'lends_to'},
        {"From": "glencore", "To": "katanga mining", 'Direction':'directed', 'Type':'lends_to'},
        {"From": "mercuria energy trading", "To": "kipushi corporation sa", 'Direction':'directed', 'Type':'lends_to'},
        {"From": "mercuria energy trading", "To": "vast resources", 'Direction':'directed', 'Type':'lends_to'},
    ] 
)

# drop rows that are missing 'To'
node_list2_exploded = node_list2_exploded[node_list2_exploded["To"].notna()]
node_list3_exploded = node_list3_exploded[node_list3_exploded["To"].notna()]

# concat
edge_list = pd.concat([node_list1_edges, node_list2_exploded, node_list3_exploded], ignore_index=True)
edge_list

                                            From                                                 To Direction          Type
0                            trafigura beheer bv                                    trafigura group  directed          owns
1                                trafigura group                           trafigura carbon trading  directed          owns
2                                trafigura group                       trafigura maritime logistics  directed          owns
3                                    vitol group                                         vitol asia  directed          owns
4                          mercuria energy group                            mercuria energy trading  directed          owns
5                          mercuria energy group                                  mercuria holdings  directed          owns
6                                   gunvor group                                   gunvor singapore  directed          owns
7                                     olam group                              olam food ingredients  directed          owns
8                                     olam group                                 olam agri holdings  directed          owns
9                          louis dreyfus company                         louis dreyfus company asia  directed          owns
10                           cofco international                      cofco international singapore  directed          owns
11                                      glencore                                 glencore singapore  directed          owns
12                                   mitsui & co        mitsui & co energy trading singapore (mets)  directed          owns
13                               shell singapore                              shell eastern trading  directed          owns
14                                       sinopec                                   unipec singapore  directed          owns
15                                       sinopec                              sinopec international  directed          owns
16                                       sinopec                    sinopec international singapore  directed          owns
17                                       sinopec                                   sinopec fuel oil  directed          owns
18                      petrochina international                 petrochina international singapore  directed          owns
19                               sinar mas group                          golden agri international  directed          owns
20                            standard chartered              standard chartered bank singapore scb  directed          owns
21                              ed&f man capital                 ed&f man capital markets singapore  directed          owns
22                          wilmar international                                       wilmar sugar  directed          owns
23                                       cargill                      cargill asia pacific holdings  directed          owns
24                                         bunge                                         bunge asia  directed          owns
25                               trafigura group                                            lex oil  directed      lends_to
26                               trafigura group                                     develop global  directed      lends_to
27                               trafigura group                             woodlawn mine holdings  directed      lends_to
28                               trafigura group                                  tarago operations  directed      lends_to
29                                  gunvor group                                             amaroq  directed      lends_to
30                                   vitol group                           uganda national oil unoc  directed      lends_to
31                                      glencore                                     katanga mining  directed      lends_to
32                       mercuria energy trading                             kipushi corporation sa  directed      lends_to
33                       mercuria energy trading                                     vast resources  directed      lends_to
34                                    reed smith  china merchants energy shipping holding singapore  directed  counsels_for
35                                    reed smith                                            sinopec  directed  counsels_for
36                                    reed smith                       trafigura maritime logistics  directed  counsels_for
37                                    reed smith      uniper global commodities se singapore branch  directed  counsels_for
38                     holman fenwick willan hfw                                         bgn energy  directed  counsels_for
39                     holman fenwick willan hfw         equatorial marine fuel management services  directed  counsels_for
40                     holman fenwick willan hfw          mitsui & co energy trading singapore mets  directed  counsels_for
41                                    clyde & co                 ed&f man capital markets singapore  directed  counsels_for
42                            stephenson harwood                        icici bank singapore branch  directed  counsels_for
43                            stephenson harwood                                         olam group  directed  counsels_for
44                            stephenson harwood                                    trafigura group  directed  counsels_for
45                      watson farley & williams                                 bw energy holdings  directed  counsels_for
46                      watson farley & williams                            hsbc singapore entities  directed  counsels_for
47                      watson farley & williams                                    trafigura group  directed  counsels_for
48                           ince & co singapore                                glory bulk carriers  directed  counsels_for
49                           ince & co singapore                tai chong cheang shipping singapore  directed  counsels_for
50                         norton rose fulbright                         louis dreyfus company asia  directed  counsels_for
51                                baker mckenzie                              shell eastern trading  directed  counsels_for
52                                baker mckenzie                                    shell singapore  directed  counsels_for
53                                hill dickinson                                    trafigura group  directed  counsels_for
54                          latham & watkins llp                              ocean network express  directed  counsels_for
55                                  rajah & tann                    sinopec international singapore  directed  counsels_for
56                                  rajah & tann                                  sumifru singapore  directed  counsels_for
57                              allen & gledhill                                        bts tankers  directed  counsels_for
58                              allen & gledhill                                           dbs bank  directed  counsels_for
59                              allen & gledhill                    jsw international tradecorp jsw  directed  counsels_for
60                              allen & gledhill           oversea-chinese banking corporation ocbc  directed  counsels_for
61                              allen & gledhill                   st telemedia global data centres  directed  counsels_for
62                              allen & gledhill                           united overseas bank uob  directed  counsels_for
63                                 drew & napier                                     metro holdings  directed  counsels_for
64                                 drew & napier                                              razer  directed  counsels_for
65                               wongpartnership                                           dbs bank  directed  counsels_for
66                               wongpartnership                                    first resources  directed  counsels_for
67                               wongpartnership                                first sponsor group  directed  counsels_for
68                                  helmsman llc                                  straits bunkering  directed  counsels_for
69                                  helmsman llc                           united overseas bank uob  directed  counsels_for
70                             blackstone & gold                                             alvari  directed  counsels_for
71                             blackstone & gold                                    avani resources  directed  counsels_for
72                         braddell brothers llp                                    bafco singapore  directed  counsels_for
73                         braddell brothers llp                basf intertrade ag singapore branch  directed  counsels_for
74                         braddell brothers llp                  the singapore medical council smc  directed  counsels_for
75                     joseph tan jude benny llp                           fti consulting singapore  directed  counsels_for
76                  dentons rodyk & davidson llp                                  boustead projects  directed  counsels_for
77                  dentons rodyk & davidson llp           oversea-chinese banking corporation ocbc  directed  counsels_for
78                  dentons rodyk & davidson llp                          thomson medical group tmg  directed  counsels_for
79                               oon & bazul llc           oversea-chinese banking corporation ocbc  directed  counsels_for
80                               oon & bazul llc                                 winson oil trading  directed  counsels_for
81                                   pdlegal llc                         louis dreyfus company asia  directed  counsels_for
82                           shook lin & bok llp              standard chartered bank singapore scb  directed  counsels_for
83                          tsmp law corporation                           halcyon agri corporation  directed  counsels_for
84                          tsmp law corporation                                ho lee construction  directed  counsels_for
85                          tsmp law corporation                                               kpmg  directed  counsels_for
86                          tsmp law corporation                                        mizuho bank  directed  counsels_for
87                          tsmp law corporation                     perennial real estate holdings  directed  counsels_for
88                          tsmp law corporation                                      seraya energy  directed  counsels_for
89                          tsmp law corporation         westbridge ventures ii investment holdings  directed  counsels_for
90                                virtus law llp              standard chartered bank singapore scb  directed  counsels_for
91                                 dennismathiew             atlantic navigation holdings singapore  directed  counsels_for
92                                 dennismathiew                               royal global exports  directed  counsels_for
93                                 asialegal llc                         louis dreyfus company asia  directed  counsels_for
94                        haridass ho & partners                                    marina offshore  directed  counsels_for
95                            pk wong & nair llc                                  maybank singapore  directed  counsels_for
96                            pk wong & nair llc                 petrochina international singapore  directed  counsels_for
97                       providence law asia llc                                     gp global apac  directed  counsels_for
98                       providence law asia llc                                   gtp advisory pac  directed  counsels_for
99                       providence law asia llc               pricewaterhousecoopers pwc singapore  directed  counsels_for
100                         lvm law chambers llc                                                cye  directed  counsels_for
101                         lvm law chambers llc                                  grabtaxi holdings  directed  counsels_for
102                         lvm law chambers llc                         ms first capital insurance  directed  counsels_for
103                         lvm law chambers llc                                   unipec singapore  directed  counsels_for
104                         lvm law chambers llc                           united overseas bank uob  directed  counsels_for
105                         lvm law chambers llc                                 winson oil trading  directed  counsels_for
106                             incisive law llc               argoglobal underwriting asia pacific  directed  counsels_for
107                             incisive law llc                  china taiping insurance singapore  directed  counsels_for
108                             incisive law llc                   great american insurance company  directed  counsels_for
109                             incisive law llc                         ms first capital insurance  directed  counsels_for
110                             incisive law llc                            qbe insurance singapore  directed  counsels_for
111                           focus law asia llc                           maersk tankers singapore  directed  counsels_for
112                                          ing                                           glencore  directed      lends_to
113                                          ing                                       gunvor group  directed      lends_to
114                                          ing                                    trafigura group  directed      lends_to
115                                          ing                                        vitol group  directed      lends_to
116                           standard chartered                                           glencore  directed      lends_to
117                           standard chartered                               marubeni corporation  directed      lends_to
118                           standard chartered                                           seatrium  directed      lends_to
119                           standard chartered                                    trafigura group  directed      lends_to
120                                     dbs bank                             agrocorp international  directed      lends_to
121                                     dbs bank                              louis dreyfus company  directed      lends_to
122                                     dbs bank                                          rio tinto  directed      lends_to
123                                     dbs bank                                    trafigura group  directed      lends_to
124                                     dbs bank                               wilmar international  directed      lends_to
125                     united overseas bank uob                                   barramundi group  directed      lends_to
126                     united overseas bank uob                                            cargill  directed      lends_to
127                     united overseas bank uob                                 musim mas holdings  directed      lends_to
128                     united overseas bank uob                                    sinar mas group  directed      lends_to
129                     united overseas bank uob                               wilmar international  directed      lends_to
130                                         mufg                                              bunge  directed      lends_to
131                                         mufg                                cofco international  directed      lends_to
132                                         mufg                                       gunvor group  directed      lends_to
133                                         mufg                                           mercuria  directed      lends_to
134                                         mufg                                six one commodities  directed      lends_to
135                                         mufg                                    trafigura group  directed      lends_to
136                                         smbc                                cofco international  directed      lends_to
137                                         smbc                                       gunvor group  directed      lends_to
138                                         smbc                              louis dreyfus company  directed      lends_to
139                                         smbc                              mercuria energy group  directed      lends_to
140                                         smbc                              olam food ingredients  directed      lends_to
141                                         smbc                                          rio tinto  directed      lends_to
142                                         smbc                                    trafigura group  directed      lends_to
143                                         smbc                                               vale  directed      lends_to
144                                         smbc                                        vitol group  directed      lends_to
145                                         smbc                               wilmar international  directed      lends_to
146                              credit agricole                                cofco international  directed      lends_to
147                              credit agricole                                       gunvor group  directed      lends_to
148                              credit agricole                              mercuria energy group  directed      lends_to
149                              credit agricole                                    trafigura group  directed      lends_to
150                              credit agricole                                        vitol group  directed      lends_to
151                                         hsbc                                           glencore  directed      lends_to
152                                         hsbc                                       gunvor group  directed      lends_to
153                                         hsbc                                 olam agri holdings  directed      lends_to
154                                         hsbc                                    sinar mas group  directed      lends_to
155                                         hsbc                                        vitol group  directed      lends_to
156                                      natixis                                cofco international  directed      lends_to
157                                      natixis                                       gunvor group  directed      lends_to
158                                      natixis                                    trafigura group  directed      lends_to
159                                      natixis                                        vitol group  directed      lends_to

In [ ]:
len(node_list1) + len(node_list2) + len(node_list3)

In [8]:
node_list1.to_csv(r"D:\commo\code\4_kumu_struct\node_list1.csv", index=False)

In [25]:
# save the 3 node lists  and edge listi
node_list1.to_csv(r"D:\commo\code\4_kumu_struct\node_list1.csv", index=False)
node_list2.to_csv(r"D:\commo\code\4_kumu_struct\node_list2.csv", index=False)
node_list3.to_csv(r"D:\commo\code\4_kumu_struct\node_list3.csv", index=False)
edge_list.to_csv(r"D:\commo\code\4_kumu_struct\edge_list.csv", index=False)

In [16]:
node_list1[node_list1['Label'].str.contains('petraco')]

                  Label    Type Description  Tier Commodity Type        Commodity Focus                                  Legal Name / ACRA UEN   HQ Country         Estimated Revenue Headcount (Global)                                                    Trade Volume (Est.) Ownership Structure Exchange                                                                     APAC offices
93  petraco oil company  trader         NaN     1         energy  crude oil | petroleum  PETRACO OIL COMPANY PTE LTD. / 201321047N (recordowl)  Switzerland  $5 million (rocketreach)      38 (linkedin)  approx. 182.5 million barrels per year (perplexity + petraco-oil.com)             private     None  8 Temasek Boulevard, #15-05A Suntec Tower 3, Singapore 038988 (petraco-oil.com)