In [46]:
import pandas as pd

# display columns without truncation
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# display rows without truncation
pd.set_option("display.max_rows", None)
pd.set_option("display.expand_frame_repr", False)

In [47]:
p1 = pd.read_csv(r"D:\commo\code\Pillar 1 - Commodities Trading Data(Active_sheet).csv", encoding='utf-8')

# drop columns
p1 = p1.drop(columns=['Known Insurance Broker', 'Singapore Presence', 'Trade Finance Relationships', 'Priority Score (1-5)', 'Done By', 'Contact Email', 'Contact Phone', 'Recent News / Expansion / Incidents', 'Key Executive (CEO/CFO/Treasurer/Risk) (SG)'])
p1 = p1.dropna(subset=["Company Name", "Commodity Focus"])
p1.fillna({"Legal Name / ACRA UEN": "Unknown", 
           "Estimated Revenue": "Unknown", 
           "Headcount (Global)": "Unknown",
           "Trade Volume (Est.)": "Unknown",
           'Listed / Exchange': "Unknown",
           'Key Executive (CEO/CFO/Treasurer/Risk) (SG)': "Unknown"}, inplace=True)
p1.rename(columns={'Notes / Next Action': 'Notes', 'Listed / Exchange': 'Exchange', 'HQ Location': 'HQ Country'}, inplace=True)
p1.fillna({}, inplace=True)
p1.head(5)

     Tier           Company Name       Commodity Type                                                                                                                                         Commodity Focus                                             Legal Name / ACRA UEN                                      HQ Country                                                                                 APAC Offices                                               Estimated Revenue Headcount (Global)                                                                                                    Trade Volume (Est.) Ownership Structure Exchange                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Notes
0  TIER 1              Trafigura                Multi                                                                  Multi-commodity (Oil & Petroleum Products, Natural Gas & LNG, Metals & Minerals, Agri)                TRAFIGURA GROUP PTE. LTD. / 201017488D (recordowl)                                       Singapore  10 Collyer Quay, #29-01/05, Ocean Financial Centre, Singapore 049315, Singapore (recordowl)            Trafigura Group: 240.3 USD bn FY2025 (trafigura.com)    5011 (linkedin)                                                          approx. 462 million metric tons (2025 annual report + claude)             Private                                                                                                                                                                                                                                                                                                                                                                               Latest acquisition (after Sep 2025): Greenergy that is owned by trafigura, acquired France's Armorine Group (trafigura 2025 annual report)
1  TIER 1                  Vitol  Energy - Hard Commo  Crude Oil, Petroleum Products, LNG, Natural gas, Biogas/BioLNG, thermal coal, metcoke, metals, power/electricity, plastics recycling (company website)                      VITOL ASIA PTE LTD. / 199001917Z (recordowl)  Switzerland (perplexity: world economic forum)                                \n128 BEACH ROAD #28-01 GUOCO MIDTOWN OFFICE SINGAPORE 189773               Turnover of $343 billion FY2025 (company website)    1990 (linkedin)                              total energy trade volume: 605 million tonnes of oil equivalent (mTOE ) (company website)             Private                                                                                                                                                                                                                                                                                                                                                                                                                              Its largest operations are in Geneva, Houston, London and Singapore. (world economic forum)
2  TIER 1               Mercuria                Multi                                                                                                                                    Energy, Metals, Agri  MERCURIA HOLDINGS (SINGAPORE) PTE. LTD. / 201808173Z (recordowl)                         Switzerland (recordowl)                 12 Marina View, #26-01, Asia Square Tower 2, Singapore 018961 (mercuria.com)                                      $618.7 Million (zoom.info)    1380 (linkedin)                                                          6M+ barrels of oil equivalent (BOE) per day (company website)             Private                                                                                                                                                                                                                             Mercuria Holdings (Singapore) Pte. Ltd. is a global commodity trader connecting essential resources to energy markets, operating globally and at scale. The company operates in over 50 countries across 5 continents and has a main trading hub located in Geneva, Switzerland. (recordowl)
3  TIER 1                 Gunvor  Energy - Hard Commo                                    Crude oil, refined petroleum products, natural gas and liquefied natural gas, biofuels, power, and carbon emissions.            GUNVOR SINGAPORE PTE. LTD. / 200606959K (acra bizfile)                       Switzerland (weforum.org)               128 Beach Road, #29-01, Guoco Midtown Office, Singapore 189773 (recordowl.com)                               US $144 billion (company website)    1035 (linkedin)                                                                                       253 million MT (company website)             Private                                                                                                                                                                                                                                                                                                                                                                       one of the world's largest independent commodities trading houses by turnover. It has trading offices in Geneva, Singapore, the Bahamas and Dubai.
4  TIER 1  Louis Dreyfus Company     Soft Commodities                                            Agri, Soft Commodities, Grains, Oilseeds, coffee, cotton, sugar, rice, juice, food & feed solutions, freight  LOUIS DREYFUS COMPANY ASIA PTE. LTD. / 199306551Z (acra bizfile)                           Netherlands (ldc.com)    12 MARINA BOULEVARD #33-03 MARINA BAY FINANCIAL CENTRE SINGAPORE 018982 (company website)  Net Sales: US$ 53.2bn FY2025 (2025.12 LDC - Integrated Report)  13,359 (linkedin)  ~100 million tonnes of products shipped annually, with volumes up 10.6% YoY in 2025 (2025.12 LDC - Integrated Report)    Private (Family)           LDC is purely agricultural, no energy commodity trading, heavily weighted towards grains & oilseeds, Profitability declined slightly in 2025 vs. 2024 (EBITDA -2.8%, Net Income -10%) despite higher revenues, due to tariff headwinds, geopolitical uncertainty, and higher finance costs, Aggressive capex cycle: capital expenditure nearly doubled to US$2.0 billion in 2025 (from US$1.0 billion in 2024), reflecting major processing and logistics expansion (2025.12 LDC - Integrated Report + claude)

In [48]:
# update existing tiers based on est. revenue
"""
Reference for the tiers:
https://sbr.com.sg/economy/in-focus/only-1-firms-exceed-100m-enterprises-cluster-below-1m-revenue

Reference for the 4 tiers which is then used to modify into 3 tiers:
- Above S$100 Mil — 4,300 firms (1%) → Tier 1
- Between S$10 Mil and S$100 Mil — 16,500 firms (5%) → Tier 2
- Between S$1 Mil and S$10 Mil — 61,100 firms (17%) → Tier 3
- Less than or equal to S$1 Mil — 276,500 firms (77%) → Tier 3

Current exchange rate (late July 2026): 1 SGD ≈ 0.775 USD

Tiers with USD equivalents:
- Tier 1: Above S$100 Mil (≈ above US$77.5 million)
- Tier 2: S$10 Mil – S$100 Mil (≈ US$7.75 million – US$77.5 million)
- Tier 3: Less than S$10 Mil (≈ less than US$7.75 million)
"""

'\nReference for the tiers:\nhttps://sbr.com.sg/economy/in-focus/only-1-firms-exceed-100m-enterprises-cluster-below-1m-revenue\n\nReference for the 4 tiers which is then used to modify into 3 tiers:\n- Above S$100 Mil — 4,300 firms (1%) → Tier 1\n- Between S$10 Mil and S$100 Mil — 16,500 firms (5%) → Tier 2\n- Between S$1 Mil and S$10 Mil — 61,100 firms (17%) → Tier 3\n- Less than or equal to S$1 Mil — 276,500 firms (77%) → Tier 3\n\nCurrent exchange rate (late July 2026): 1 SGD ≈ 0.775 USD\n\nTiers with USD equivalents:\n- Tier 1: Above S$100 Mil (≈ above US$77.5 million)\n- Tier 2: S$10 Mil – S$100 Mil (≈ US$7.75 million – US$77.5 million)\n- Tier 3: Less than S$10 Mil (≈ less than US$7.75 million)\n'

In [49]:
# Tier 1: Above S$100 Mil (≈ above US$77.5 million)
# Tier 2: S$10 Mil – S$100 Mil (≈ US$7.75 million – US$77.5 million)
# Tier 3: Less than S$10 Mil (≈ less than US$7.75 million)

# tier 1: 19, 20, 21, 22, 23, 27, 28,29, 31, 32, 33, 41, 43, 44, 45,
#          48, 50, 53, 54, 58, 60, 63, 64, 65, 66, 67, 70, 71, 72, 74, 78, 79, 80, 81, 82, 83
#            ,84, 85, 86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105,
# tier 2: 46, 56, 106
# tier 3: 25, 40, 42, 68, 69, 73, 89


tier1 = [19, 20, 21, 22, 23, 27, 28,29, 31, 32, 33, 41, 43, 44, 45,
         48, 50, 53, 54, 58, 60, 63, 64, 65, 66, 67, 70, 71, 72, 74, 75, 76, 78, 79, 80, 81, 82, 83
        ,84, 85, 86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105]
tier1_companies = p1.loc[tier1, "Company Name"].tolist()

tier2 = [46, 56, 57, 61, 62, 106]
tier2_companies = p1.loc[tier2, "Company Name"].tolist()

tier3 = [25, 40, 42, 68, 69, 73, 89]
tier3_companies = p1.loc[tier3, "Company Name"].tolist()

for index, row in p1.iterrows():
    if row["Company Name"] in tier1_companies:
        p1.at[index, "Tier"] = 'TIER 1'
    elif row["Company Name"] in tier2_companies:
        p1.at[index, "Tier"] = 'TIER 2'
    elif row["Company Name"] in tier3_companies:
        p1.at[index, "Tier"] = 'TIER 3'
        
#check the changes        
p1.loc[tier3]

      Tier                   Company Name                                              Commodity Type                                                                                                                               Commodity Focus                                                                       Legal Name / ACRA UEN                      HQ Country                                                                         APAC Offices                     Estimated Revenue    Headcount (Global)                                                    Trade Volume (Est.) Ownership Structure Exchange                                                                                                                                                                                                                                                                          Notes
25  TIER 3                  Straits Grain                                            Soft Commodities                                                                                                                                  Grains, Feed                                THE STRAITS INTERNATIONAL PTE. LTD. / 201025898Z (recordowl)  Singapore (straitsintl.com.sg)   4008 Ang Mo Kio Avenue 1, Techplace 1 #02-15 Singapore 569625 (straitsintl.com.sg)  $2M – $5M USD  (2024-26) (google AI)     8 (2024) (tracxn)                                                                Unknown             Private                                                                                                                            originate and buy physical agri-commodities, focus industries are animal and aqua feeds, flour milling, food manufacturing, and oils and fats manufacturing.
40  TIER 3                    Straits Oil                                         Energy - Hard Commo                                                                                                                            Petroleum Products                                        STRAITS BUNKERING PTE. LTD. / 201415157M (recordowl)          Singapore (perplexity)  9 RAFFLES PLACE, #17-20, REPUBLIC PLAZA II, SINGAPORE 048619 (straitsbunkering.com)                <$5 Million (zoominfo)         46 (linkedin)               approx. 6,700-10,000 metric tonnes annually (perplexity)             Private           straits oil pte ltd is struck off (recordowl). Straits Bunkering Pte Ltd trades petroleum products. Straits bunkering pte ltd is a leading provider of bunkering services in Singapore and Malaysian waters, specialized in the supply of Marine Fuel Oil and Marine Gas Oil.
42  TIER 3                    Petraco Oil                                         Energy - Hard Commo                                                                                                                 Crude Oil, Petroleum Products                                       PETRACO OIL COMPANY PTE LTD. / 201321047N (recordowl)   Switzerland (petraco-oil.com)      8 Temasek Boulevard, #15-05A Suntec Tower 3, Singapore 038988 (petraco-oil.com)              $5 million (rocketreach)         38 (linkedin)  approx. 182.5 million barrels per year (perplexity + petraco-oil.com)             Private
68  TIER 3          Bary Chemical Pte Ltd                                                       Multi                                                                                Coal, Fertlizers, Bauxite, Iron Products, Nickel Ore (bary.sg)                                            BARY CHEMICAL PTE. LTD. / 200700627M (recordowl)             Singapore (bary.sg)                             114 LAVENDER STREET,SINGAPORE 338729,SINGAPORE (bary.sg)          < $5 million USD (google ai)  11 to 50 (google ai)                                         annual ave. > 10 Mmt (bary.sg)             Private  Unknown                                                                                                                                                                                                    Bary Chemical has established a subsidiary Bary Commodity. https://bary.sg/
69  TIER 3  Mahkota Oils & Fats Pte. Ltd.                                            Soft Commodities                                                Palm Oil Products (Crude Palm Oil, RBD Palm Olein, and Palm Fatty Acid Distillate) (google ai)                                      MAHKOTA OILS & FATS PTE. LTD. / 202320748R (recordowl)           Indonesia (google ai)       491B RIVER VALLEY ROAD,, #11-03 VALLEY POINT, SINGAPORE, 248373, SG (linkedin)                ~$342,220 (prospeo.io)  1 to 10 (prospeo.io)                                                                Unknown             Private  Unknown                                                                                                                                 The parent company of Mahkota Oils & Fats Pte. Ltd. is the Indonesian palm oil processing company PT Mahkota Group Tbk (IDX: MGRO) (google ai)
73  TIER 3    Oriental Energy & Resources                                                       Multi                           Mineral Resources (Copper, Nickel, Aluminum, etc.), CPO (Crude Palm Oil) and Refined Palm Oil (oriental-energy.com)  ORIENTAL ENERGY PTE LTD / 200808445C & ORIENTAL RESOURCES PTE LTD / 202100630W (recordowl)            Singapore (linkedin)           7500A Beach Road #08-312 The Plaza, Singapore 199591 (oriental-energy.com)                      ~$3.5M (prospeo)         28 (linkedin)                                                                Unknown             Private  Unknown                                                                                                                                                                                                                                                        www.oriental-energy.com
89  TIER 3     Bary Commodities Pte. Ltd.  Energy and Petrochemicals Commodities (gemini) & (bary.sg)  Coal (Energy),Ores & Minerals (Industrial Mining): Nickel Ore, Brucite, Bauxite, Iron Products,Fertilizers (Agricultural Chemicals) (gemini)                                     Bary Chemical Pte Ltd/ 201807001W (recordowl) (bary.sg)  Republic of Singapore (Gemini)                             114 LAVENDER STREET,SINGAPORE 338729,SINGAPORE (bary.sg)     under $5 million USD  (google ai)     10 to 50 (Gemini)                       average of over 10 Million metric tons (bary.sg)             private  Unknown                                                                                                                                Bary doesn't has their personal profile : linkedin, facebook,..(Google AI), for legal name in recordowl and their website have difference name.

In [50]:
#can only be run after fixing the tiers
p1 = p1[p1["Company Name"] != "New companies"]

In [51]:
p1.shape

(104, 13)

In [52]:
p1.info()

<class 'pandas.DataFrame'>
Index: 104 entries, 0 to 106
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Tier                   104 non-null    str
 1   Company Name           104 non-null    str
 2   Commodity Type         104 non-null    str
 3   Commodity Focus        104 non-null    str
 4   Legal Name / ACRA UEN  104 non-null    str
 5   HQ Country             104 non-null    str
 6   APAC Offices           104 non-null    str
 7   Estimated Revenue      104 non-null    str
 8   Headcount (Global)     104 non-null    str
 9   Trade Volume (Est.)    104 non-null    str
 10  Ownership Structure    104 non-null    str
 11  Exchange               104 non-null    str
 12  Notes                  104 non-null    str
dtypes: str(13)
memory usage: 11.4 KB

In [53]:
p1.isnull().sum() # 0 null values

Tier                     0
Company Name             0
Commodity Type           0
Commodity Focus          0
Legal Name / ACRA UEN    0
HQ Country               0
APAC Offices             0
Estimated Revenue        0
Headcount (Global)       0
Trade Volume (Est.)      0
Ownership Structure      0
Exchange                 0
Notes                    0
dtype: int64

In [54]:
# change all tier from str to int
tier_mapping = {'TIER 1': 1, 'TIER 2': 2, 'TIER 3': 3}
if p1['Tier'].dtype == 'object' or p1['Tier'].dtype == 'str':
    p1['Tier'] = p1['Tier'].str.strip()
    p1['Tier'] = p1['Tier'].map(tier_mapping)
p1['Tier'].dtype
p1["Tier"].unique()  # 1,2,3

array([1, 2, 3])

In [55]:
# CHECK 'Company Name'
unique_names = p1['Company Name'].unique().tolist()
len(unique_names) #104
len(p1["Company Name"].tolist())  # 104

#'Trafigura' parent of 'Trafigura Carbon Trading'
#'Bary Chemical Pte Ltd' parent of 'Bary Commodities Pte. Ltd.'

# update company names to match the names in the other datasets
p1.loc[p1["Company Name"] == "Olam International", 'Company Name'] = 'Olam Group'
p1.loc[p1["Company Name"] == "HD HYUNDAI MARINE SOLUTION SINGAPORE PTE LTD HD", "Company Name"] = "HD HYUNDAI MARINE SOLUTION SINGAPORE PTE LTD"
p1.loc[p1["Company Name"] == "olam agri (spun off)", "Company Name"] = "olam agri"
p1.loc[p1["Company Name"] == "noble group (restructured)", "Company Name"] = "noble group"
p1.loc[p1["Company Name"] == "century commodities solution pte ltd (formerly china coal solution singapore)", "Company Name"] = "century commodities solution pte ltd"

p1['Company Name'] = p1['Company Name'].str.replace('.', '', regex=False).str.strip()
# p1["Company Name"].tolist()
len(unique_names)

104

In [56]:
# check 'Commodity Type'
# create a copy
if "Commodity Type copy" not in p1.columns:
    p1["Commodity Type copy"] = p1["Commodity Type"].copy()

In [57]:
# check 'Commodity Type'
# remove brackets and their contents
p1["Commodity Type copy"] = p1["Commodity Type copy"].str.replace(r"\(.*?\)", "", regex=True)
# remove whitespace and convert to lowercase
p1["Commodity Type copy"] = p1["Commodity Type copy"].str.lower().str.strip()

# update the unique values
commodity_mapping = {
    "energy and petrochemicals commodities  &": "energy and petrochemicals",
    "energy and petrochemicals commodities": "energy and petrochemicals",
    "energy and petrochemical commodities": "energy and petrochemicals",
    "energy - hard commo": "energy or hard/metals",
    "soft commodities": "soft/agricultural",
    "hard commo": "hard/metals",
    "energy commo": "energy",
    "energy and soft commodities": "energy and soft/agricultural",
    "multi": "multi (>2 types)",
}

p1["Commodity Type copy"] = p1["Commodity Type copy"].replace(commodity_mapping)

unique_commo_types = p1["Commodity Type copy"].unique().tolist()
unique_commo_types

# energy or hard/metals become ['energy', 'hard/metals']
# energy and petrochemicals become ['energy', 'petrochemicals']
# energy and soft/agricultural become ['energy', 'soft/agricultural']
import re
def split_commodity_types(commodity_type_str):
    if pd.isna(commodity_type_str):
        return [] 
    elif commodity_type_str in ['multi (>2 types)', 'petrochemicals', 'soft/agricultural', 'emerging', 'hard/metals', 'energy']:
        return [commodity_type_str]
    else:
        parts = re.split(r'\s+and\s+|\s+or\s+', commodity_type_str)
        return [p.strip() for p in parts]

p1['Commodity Type'] = p1['Commodity Type copy'].apply(split_commodity_types) #can run only once, comment out after running

# get the unique values of the updated column where each row is a list of str, update() use with set() to append only unique values
unique_values2 = set()
for list in p1['Commodity Type']:
    unique_values2.update(list)
print(unique_values2)

{'petrochemicals', 'multi (>2 types)', 'soft/agricultural', 'hard/metals', 'energy', 'emerging'}

In [58]:
# drop the copy column
p1 = p1.drop(columns={"Commodity Type copy"})

In [59]:
#strip whitespace from commodity focus
p1['Commodity Focus'] = p1['Commodity Focus'].str.strip()
p1['Commodity Focus'].tail()

102    alumina, electrolytic aluminum, coking coal, thermal coal, copper, lead, zinc, rare and precious metals, bauxite, copper concentrate, iron ore (https://www.chalco.com.cn/en/sctxen/cpjyen/)
103                                                                                                   manganese ore, manganese alloys, Ferrosilicon, Silicon Metal (OMH 2024 annual report +claude)
104                                                                                                                    thermal coal, petroleum products, fuels, transition energy products (google)
105                                                                                                                      crude oil, feedstocks, refined petroleum products, petrochemicals (google)
106                                                     Stainless steel plates, stainless steel coils, stainless steel sheets, hot-rolled steel, cold-rolled steel, metals, and metal ores (gemini)
Name: Commodity Focus, dtype: str

In [ ]:
# update the commodity type based on the commodity focus
focus_type = p1[['Commodity Focus','Commodity Type']]
focus_type #for checking only
# {'energy', 'emerging', 'multi (>2 types)', 'petrochemicals', 'soft/agricultural', 'hard/metals'}

# use .loc because indices are not in order
# energy: [3, 15, 16, 17, 38, 40, 41, 42, 43, 48, 49, 50, 51, 52, 53, 54]
p1.loc[[3, 15, 16, 17, 38, 40, 41, 42, 43, 48, 49, 50, 51, 52, 53, 54],'Commodity Type'] = p1.iloc[[3, 15, 16, 17, 38, 40, 41, 42, 43, 48, 49, 50, 51, 52, 53, 54]]['Commodity Type'].apply(lambda lst: [type for type in lst if type != 'hard/metals'])

# multi: [1, 8, 9, 39, 76, 89]
p1.loc[[1, 8, 9, 39, 76, 89], 'Commodity Type'] = p1.loc[[1, 8, 9, 39, 76, 89], 'Commodity Type'].apply(lambda lst: 'multi (>2 types)')

# energy & petrochemical: [14, 72, 75]
p1.loc[[14, 72, 75], "Commodity Type"] = p1.loc[[14, 72, 75], "Commodity Type"].apply(lambda lst: ["energy", "petrochemicals"])

# engery & soft: [18, 57, 92]
p1.loc[[18, 57, 92], "Commodity Type"] = p1.loc[[18, 57, 92], "Commodity Type"].apply(lambda lst: ['energy','soft/agricultural'])

# hard: [31, 32, 33, 34, 56, 60]
p1.loc[[31, 32, 33, 34, 56, 60], 'Commodity Type'] = p1.loc[[31, 32, 33, 34, 56, 60], 'Commodity Type'].apply(lambda lst: [item for item in lst if item != 'energy'])

# hard & soft: [36, 63, 64, 73]
p1.loc[[36, 63, 64, 73], "Commodity Type"] = p1.loc[[36, 63, 64, 73], "Commodity Type"].apply(lambda lst: ["hard/metals", 'soft/agricultural'])

# hard & petrochemicals: 82
p1.loc[[82], "Commodity Type"] = p1.loc[[82], "Commodity Type"].apply(lambda lst: ["hard/metals", "petrochemicals"])

# petrochemicals & soft: 45
p1.loc[[45], "Commodity Type"] = p1.loc[[45], "Commodity Type"].apply(lambda lst: ["petrochemicals", 'soft/agricultural'])

# energy & hard: [68, 74, 90]
p1.loc[[68, 74, 90], "Commodity Type"] = p1.loc[[68, 74, 90], "Commodity Type"].apply(lambda lst: ['energy', "hard/metals"])

# turn all list into comma separated string
p1["Commodity Type"] = p1["Commodity Type"].apply(
    lambda x: ", ".join(x) if isinstance(x, list) else x
)

# check
p1.loc[[68, 74, 90], "Commodity Type"]

    Tier                      Company Name Commodity Type                                                                                         Commodity Focus                                        Legal Name / ACRA UEN                              HQ Country                                                                                       APAC Offices                                                                                Estimated Revenue Headcount (Global)                                          Trade Volume (Est.)  Ownership Structure Exchange                                                                                                                            Notes
31     1                     Gerald Metals  [hard/metals]                                                                               Base Metals, Concentrates          GERALD SINGAPORE PTE. LTD. / 201135083W (recordowl)                         UK (perplexity)                                     80 RAFFLES PLACE #32-01 UOB PLAZA SINGAPORE 048624 (recordowl)                                      Annual turnover of approximately US$10 billion (perplexity)     247 (linkedin)  More than 5.5 million tonnes of metal annually (perplexity)              Private                                                                   Is part of Gerald Group. SG address is one of the operating companies.
32     1                            Traxys  [hard/metals]                                                                          Specialty Metals, Minor Metals          TRAXYS SINGAPORE PTE. LTD. / 202215010H (recordowl)                   Luxembourg (linkedin)                                             73 Tras Street #04-01, SINGAPORE , 079012 (traxys.com)                                                              $10.0B+ annual revenue (traxys.com)     393 (linkedin)                        ~ 30 million MT annually (perplexity)  Private (PE-backed)           2 april 2026: Luxembourg, Traxys Group completes acquisition of Carbomax AB through the purchase of 100% of Comax2 (traxys.com)
33     1                   Wogen Resources  [hard/metals]                                                                          Metals, Minerals, Concentrates    WOGEN SOUTH EAST ASIA PTE. LTD. / 202516994M  (recordowl)  Singapore; UK (global hq) (perplexity)                                               68 CIRCULAR ROAD #02-01 SINGAPORE 049422 (recordowl)  annual turnover well in excess of $500 million in physically delivered commodities (perplexity)      45 (linkedin)                                                      Unknown              Private                                                                                       Singapore is not listed in Wogen Resources website.
34     2                    MRI Trading AG  [hard/metals]  Base Metals, non-ferrous ores, concentrates, refined and precious metals and their related by-products              MRI Group Pte. Ltd / 201026486D (sg.ltddir.com)                  Switzerland (linkedin)  MRI Group Pte. Ltd, 37-06/07, OCBC Tower East, 65 Chulia Street, Singapore 049513 (mri-group.com)                                                                     $18.7 Million (zoominfo.com)      83 (linkedin)                    ~  1-2 million metric tonnes (perplexity)              Private                                                                           MRI Trading AG is CWT group's Commodity Marketing business arm.
56     2  Triland Metals Singapore Pte Ltd  [hard/metals]                                                            Base Metals, precious metals, ferrous metals  TRILAND METALS SINGAPORE PTE. LTD. / 201230406H (recordowl)                London, UK (triland.com)                            3, Temasek Ave, #33-03 Centennial Tower, Singapore 039190 (triland.com)                     annual net brokerage turnover ave. $65 million – $78 million USD (google ai)      92 (linkedin)                                >10 millions mt (group level)              Private  Unknown           Triland Metals is a 100% subsidiary of Mitsubishi Corporation, specialising in base, precious and ferrous derivatives.
60     1                               IXM  [hard/metals]                                          Copper, lead, zinc concentrates & refined metals (en.cmoc.com)                       IXM PTE. LTD. / 200610582N (recordowl)      Geneva, Switzerland (ixmetals.com)                    IXM Pte. Ltd., 3 Church Street, #24-03 Samsung Hub, Singapore 049483, Singapore                                                                        +25 BN USD (ixmetals.com)     370 (linkedin)                     4.17 million tonnes FY2025 (en.cmoc.com)              Private  Unknown                      IXM is a wholly-owned subsidiary of CMOC. https://en.cmoc.com/html/Business/IXM/. https://www.ixmetals.com/

In [ ]:
# standardize the commodity focus, organized details
p1['Commodity Focus'].unique().tolist()
#'Multi-commodity (Oil & Petroleum Products, Natural Gas & LNG, Metals & Minerals, Agri)' = ['oil', 'petroleum','natural gas', 'LNG', 'metals', 'soft/agricultural']
# 'Crude Oil, Petroleum Products, LNG, Natural gas, Biogas/BioLNG, thermal coal, metcoke, metals, power/electricity, plastics recycling (company website)',=['crude oil','petroleum','LNG', 'natural gas', 'biogas/bioLNG', 'thermal coal', 'metcoke', 'metals', 'power', 'plastics']
# 'Energy, Metals, Agri' = ['energy','metals','soft/agricultural']
# 'Crude oil, refined petroleum products, natural gas and liquefied natural gas, biofuels, power, and carbon emissions.',=['crude oil', 'refined petroleum products', 'natural gas', 'LNG', 'biofuels', 'power', 'carbon']
# 'Agri, Soft Commodities, Grains, Oilseeds, coffee, cotton, sugar, rice, juice, food & feed solutions, freight',= 'Agri, Soft Commodities, Grains, Oilseeds, coffee, cotton, sugar, rice, juice, food & feed solutions, freight',=['grains','oilseeds', 'coffee','cotton', 'sugar', 'rice', 'juice']
# 'Palm Oil, Sugar, Grains, Oilseeds', = ['palm oil', 'sugar', 'grain', 'oilseeds']
# 'Agri, Food, Industrial Raw Materials, cocoa, coffee, cotton, nuts and spices', = ['cocoa', 'coffee', 'cottons', 'nuts', 'spices']
#'Grains, Oilseeds, Sugar, Cotton', = ['grains', 'oilseeds', 'sugar', 'cotton']
# 'Grains, Oilseeds, Metals, Energy',=['grains','oilseeds','metals','energy']
# 'Metals, Energy, Agri',= ['energy','metals','soft/agricultural']
# 'Grains, Oilseeds, Agri', = ['grains','oilseeds']
# 'Grains, Oilseeds, Sugar',= ['grains','oilseeds', 'sugar']
# 'Agri, Energy, Metals, Chemicals', = ['energy','soft/agricultural','chemicals','metals']
# 'Energy, Metals, Chemicals, Agri',= ['energy','soft/agricultural','chemicals','metals']
# 'Crude Oil, LNG, Petroleum Products, Petrochemical & Feedstock, International chartering, Derivatives',= ['crude oil', 'LNG', 'petroleum', 'petrochemicals', 'feedstock']
# 'Crude Oil, LNG, Petroleum Products', = ['crude oil', 'LNG', 'petroleum']
# 'Crude Oil, Gas, Petroleum Products',= ['crude oil', 'LNG', 'petroleum', 'gas']
# 'Crude Oil, LNG, Renewables', = ['crude oil', 'LNG', 'renewables']
# 'Energy, Chemicals, Petroleum, Agri', = ['petroleum','soft/agricultural','chemicals']
# 'Grains, Pulses, Oilseeds, wheat, sugar, cotton, nuts',= ['grains', 'pulses', 'oilseeds', 'wheat', 'sugar', 'cotton', 'nuts']
# 'Palm Oil, Laurics', = ['palm oil', 'laurics']
# 'Palm Oil, Oleochemicals', = ['palm oil', 'oleochemicals']
# 'Edible Oils, Agri', = ['edible oils']
# 'Soybeans, Corn, Wheat, Canola, Barley, Rye, Pulses , Lentils, Non-GMO & Organic grains, etc.', = ['soybeans', 'corn', 'wheat', 'canola', 'barley', 'rye', 'pulses', 'lentils', 'grains']
# 'Grains, Feed', = ['grains', 'feed']
#  'Agri, Food Ingredients', = ['food ingredients']
# 'Grains, Edible Oils, Cotton, Cocoa', = ['grains', 'edible oils', 'cotton', 'cocoa']
#  'Sugar', = ['sugar']
# 'Soft Commodities', = ['soft/agricultural']
#'Multi-commodity', = ['Unknown']
#'Base Metals, Concentrates' = ['base metals', 'concentrates']
# 'Specialty Metals, Minor Metals', = ['specialty metals', 'minor metals']
# 'Metals, Minerals, Concentrates', = ['metals', 'minerals', 'concentrates']
# 'Base Metals, non-ferrous ores, concentrates, refined and precious metals and their related by-products', = ['base metals', 'non-ferrous metals', 'concetrates', 'refined metals', 'precious metals']
#'Coal, Minerals, Cement', = ['coal', 'minerals', 'cement']
# 'Minerals, Mining, Agri', = ['minerals', 'soft/agricultural']
# 'Iron Ore, Coal, Minerals', = ['iron ore', 'coal', 'minerals']
# 'Crude, Fuel Oil, Naphtha, LNG, Gasoil, Gasoline', = ['crude oil', 'fuel oil', 'naphtha', 'LNG', 'gasoline', 'gasoil']
# 'Petroleum Products, Bunkers, heating oil, fuel oil, middle distillates, crude oil, brent oil ,fuel oil, LPG, Naphtha, Palm oil, Biofuels, Petrochemicals, Gasoline, LNG, Rubber', = ['petroleum', 'bunkers', 'heating oil', 'fuel oil', 'distillates', 'crude oil', 'brent oil', 'LPG', 'naphtha', 'palm oil', 'biofuels', 'petrochemicals', 'gasoline', 'rubber']
# 'Petroleum Products', = ['petroleum']
# 'Crude Oil, LNG', = ['crude oil', 'LNG']
# 'Crude Oil, Petroleum Products', = ['crude oil','petroleum']
# 'Petrochemicals, Polymers', = ['petrochemicals', 'polymers']
# 'Chemicals, Agri', = ['chemicals', 'soft/agricultural']
# 'Chemicals, Solvents', = ['chemicals', 'solvents']
# 'Rice, edible oil, sugar, coffee', = ['rice', 'edible oil', 'sugar', 'coffee']
# 'Oil Products', = ['oil']
# 'LNG, Gas', = ['LNG', 'gas']
# 'Energy, Oil Products', = ['oil']
# 'Crude Oil, Products', = ['crude oil']
# 'Green Commodities, Biofuels', = ['biofuels']
# 'Base Metals, precious metals, ferrous metals', = ['base metals', 'precious metals', 'ferrous metals']
# 'vegetable oil, renewable fuel, oleochemicals (apicalgroup.com)', = ['vegetable oil', 'renewable fuel', 'oleochemicals']
# 'Carbon credits', = ['carbon']
# 'Copper, lead, zinc concentrates & refined metals (en.cmoc.com)', = ['copper', 'lead', 'zinc', 'refined metals']
# 'Coal, iron ore, copper, aluminum, nickel, lithium, precious metals (mitsubishicorp.com)', = ['coal', 'iron ore', 'copper', 'aluminum', 'nickel', 'lithium']
# 'Base metal (Zinc, Lead, Aluminum, Copper, etc), chemical commodity (kztrading.co.kr)', = ['zinc', 'lead', 'aluminum', 'copper', 'petrochemicals']
# 'Thermal, coking, and met coal; iron ore, fluxes, and fertilizer raw materials; ferro-alloy products (manganese, silicon, vanadium, titanium); and base materials like nickel and tin, Pulses and beans (pigeon pea, black lentils, green mung beans); feed meals (soya bean meal, rape seed meal); sugar, rice, grains, and other commodities.  (cbonds.com)', = ['thermal coal', 'coking coal', 'met coal', 'iron ore', 'fluxes', 'fertilizer raw materials', 'manganese', 'silicon', 'vanadium', 'titanium', 'nickel', 'tin', 'pulses', 'beans', 'feed meals', 'sugar', 'rice', 'grains']
# 'Pulses, Grains, Oilseeds, Rice, Tea and Sugar. Fertilizers and Sulphur,  Thermal Coal, Coking Coal and Petroleum Coke, iron ore, Non-Ferrous( abgtrading.com)',= ['pulses', 'grains', 'oilseeds', 'rice', 'tea', 'sugar', 'fertilizers', 'sulphur', 'thermal coal', 'coking coal', 'petroleum coke', 'iron ore', 'non-ferrous metals']
# 'Energy(Natural Gas, LNG, Solar Energy, Wind Energy, Hydrogen, etc.), Steel and Raw Material for Steel, Secondary Battery Materials, Grain, Oils and Fats, Cotton, Bioplastics, Eco-friendly Car Parts (poscointl.com)', = ['natural gas', 'LNG', 'solar', 'wind energy', 'hydrogen', 'steel', 'battery materials', 'grain', 'oil', 'fats', 'cotton', 'bioplastics', 'car parts']
# 'sugar, rice, and oil and fat products (https://www.sec.gov/Archives/edgar/data/1949478/000168316826004029/davis_ex9901.htm)', = ['sugar', 'rice', 'oil', 'fats']
# 'Coal (https://www.itochu.co.jp/en/business/metal/project/13.html)' = ['coal']
#  'Coal, Fertlizers, Bauxite, Iron Products, Nickel Ore (bary.sg)', = ['coal', 'fertilizers', 'bauxite', 'iron', 'nickel ore']
#  'Palm Oil Products (Crude Palm Oil, RBD Palm Olein, and Palm Fatty Acid Distillate) (google ai)', = ['palm oil']
# 'Coal & Carbon, Iron & Steel Raw Materials, Battery & Base Metals, Basic Chemicals (Refinery/Cracker Bulk Petrochemicals), Intermediate & Specialty Chemicals, Oils & Fats, Sugar, Dairy & Coffee (Gemini)', = ['coal', 'carbon', 'iron', 'steel', 'base metals', 'chemicals', 'oil', 'fats', 'sugar', 'dairy', 'coffee']
# 'Steel, Energy & Resources, Chemicals & Petroleum  (gemini)', = ['steel', 'energy', 'chemicals', 'petroleum']
# 'Crude Oi, Petroleum Products, Marine & Biofuels, Aromatics, Polymers (gemini)', = ['crude oil', 'petroleum', 'biofuels', 'aromatics', 'polymers']
# 'Mineral Resources (Copper, Nickel, Aluminum, etc.), CPO (Crude Palm Oil) and Refined Palm Oil (oriental-energy.com)', = ['copper', 'nickel', 'aluminum', 'palm oil']
# 'crude oil and refined products (naphtha, gasoline, gasoil, jet fuel and fuel oil), asphalt/bitumen, LPG, sulphur and base oil (spc.com.sg)', = ['crude oil', 'naphtha', 'gasoline', 'gasoil', 'fuel oil', 'asphalt/bitumen', 'LPG','sulphur', 'base oil']
# 'crude oil, LNG, Refined oil products, chemical products, fuel oil, refining by-products, lubricants, catalysts (sinopecgroup.com)', = ['crude oil', 'LNG', 'oil', 'chemicals', 'fuel oil']
# 'Coal, PDEB, EVOH, Rubber additives, White oil, Asphalt (gemini)', = ['coal', 'PDEB', 'EVOH', 'rubber additives', 'white oil', 'asphalt']
# 'Marine Fuel oil, gas oil, diesel, motor gasoline, green fuels (gemini)', = ['fuel oil', 'gas oil', 'diesel', 'motor gasoline', 'green fuels']
# 'copper, niobium, aluminum, iron ore, and steel, etc (metal.citic)', = ['copper', 'niobium', 'aluminum', 'iron ore', 'steel']
# 'Coal, ferrous metals, iron ore, derroalloys, ferrous raw materials, non-ferrous metals, base metals (gemini)', = ['coal', 'ferrous metals', 'iron ore', 'ferroalloys', 'non-ferrous metals', 'base metals']
# Idk how to annonate: 'High-grade iron ore, Coking coal, Metallurgical coal, Niobium, Gallium, Neodymium, Light rare earths, Dysprosium, Heavy rare earths, Terbium, Fluorite, Ferrosilicon, Bentonite, Bauxite, Casting coke, Petroleum coke, Iron scrap, Copper, Alumina, Platinum, Palladium, Methanol, Industrial salts, Plastic resins, Biochemicals, Green polyethylene, Biomass resins, Dicyclopentadiene, SBR Latex, ABS Resins, Grains, Wheat, Corn, Animal feed raw materials, Sugar, Coffee beans, Timber, Logs, Woodchips, Plywood, Biomass fuel, Paper products, Chemical fertilizers, Frozen beef, Seafood products, Crude oil, Natural gas, Liquefied Natural Gas, Biomethane, Nuclear fuel (gemini)',
# 'carbon steel, stainless steel, polymers, methanol, organic & inorganic chemicals, fine chemicals, sodium cyanide, mining tires & grinding media, nitrogen fertilizers, compound fertilizers, phosphate fertilizers, non-ferrous metals/concentrates such as copper concentrate, zinc concentrate, precious metal concentrate, non-ferrous metals (refined metal) such as electrolytic copper , etc (trading.samsungcnt.com)', = ['steel', 'polymers', 'methanol', 'fertilizers', 'copper', 'zinc', 'ferrous metals', 'precious metals', 'non-ferrous metals']
# 'thermal coal, nickel, bauxite, copper, petrochemicals, steel products, oils, IT components, crude palm oil, oil palm fruits, biofuels (lxinternational.com)', = ['thermal coal', 'nickel', 'bauxite', 'copper', 'petrochemicals', 'steel', 'oils', 'palm oil', 'biofuels']
# 'petroleum products, raw materials & semi products, flat steel products, long steel products, Steel Pipes & Tubes, Stainless Steel Products, Polymers (Synthetic Resins), Chemical Fertilizers (hyundaicorp.com)', = ['petroleum', 'steel', 'polymers', 'fertilizers']
# 'LNG, crude oil, pipeline natural gas, condensate, LPG, carbon-offset LNG, ammonia & hydrogen (google ai)', = ['LNG', 'crude oil', 'natural gas', 'condensate', 'LPG', 'carbon', 'gas']
# 'thermal coal, metallurgical coal (coking coal), third-party coal', = ['coal']
# 'palm oil, sugar cane, rubber, other crops (gemini)', = ['palm oil', 'sugar cane', 'rubber']
# 'Chemicals, Energy, Oil and gas (gemini)', = ['chemicals', 'gas', 'oil']
# 'Coal (Energy),Ores & Minerals (Industrial Mining): Nickel Ore, Brucite, Bauxite, Iron Products,Fertilizers (Agricultural Chemicals) (gemini)', = ['coal', 'ores', 'fertilizers']
# 'Wholesale of metals and metal ores, Wholesale of fuels and related products (gemini)', = ['metals', 'ores', 'fuel oils']
#  'Crude Oils, Gasoline, Gasoil, Decant Oil, HVR (High Viscosity Residue), LSCR (Low Sulfur Crude Residue), LSFO (Low Sulfur Fuel Oil), MFO (Marine Fuel Oil), Vacuum Residue, Petrochemicals (pimd.pertamina.com/business-portfolio/)', = ['crude oils', 'gasolline', 'gasoil', 'oils', 'petrochemicals']
# 'Palm oil, Palm olein, Palm stearin, Palm kernel oil, Lauric products, Palm kernel cake, Bakery fats, Margarines, Frying oils, Rubber, Biomass, Biogas (gemini)', = ['palm oil', 'palm products', 'fats', 'margarines', 'oils', 'rubber', 'biomass', 'biogas']
# 'Angle Bar, Flat Bar, Round Bar, Square Bar, Deformed Bar, Steel Plate, Hollow Section, Channels, Beams/Columns, Pipes, Grating (hgmetal.com)', = ['steel']
# idk how to annonate: 'high-grade iron ore, Coking coal, Metallurgical coal, Niobium, Gallium, Neodymium, Light rare earths, Dysprosium, Heavy rare earths, Terbium, Fluorite, Ferrosilicon, Bentonite, Bauxite, Casting coke, Petroleum coke, Iron scrap, Copper, Alumina, Platinum, Palladium, Methanol, Industrial salts, Plastic resins, Biochemicals, Green polyethylene, Biomass resins, Dicyclopentadiene, SBR Latex, ABS Resins, Grains, Wheat, Corn, Animal feed raw materials, Sugar, Coffee beans, Timber, Logs, Woodchips, Plywood, Biomass fuel, Paper products, Chemical fertilizers, Frozen beef, Seafood products, Crude oil, Natural gas, Liquefied Natural Gas, Biomethane, Nuclear fuel (gemini)'
# 'Wheat, Soybeans, Wheat bran, Wheat starch (gemini)', = ['wheat', 'soybeans']
# 'crude oil, petroleum products and feedstock (eneos.asia)', =['crude oil', 'petroleum', 'feedstock']
# 'Crude, Gasoline, Naphtha, Middle Distillate, Fuel Oil, Petrochemical, Biodiesel, Carbon Credit  (idemitsu.com)', = ['crude oil', 'gasoline', 'naphtha', 'distillates', 'fuel oils', 'petrochemicals', 'biodiesel', 'carbon']
# 'crude oil, petroleum products (cosmo-energy.co.jp)', = ['crude oil', 'petroleum']
# 'iron ore, steel trading (jfe-shoji.co.jp)', = ['iron ore', 'steel']
# 'thermal coal, coking coal, coke, crude oil, fuel oil, middle distillates, and more, renewable energy such as Brown Grease Methyl Ester (BGME), Used Cooking Oil (UCO), Palm Oil Mill Effluent (POME), Fatty Acid Methyl Ester (FAME), and Used Cooking Oil Methyl Ester (UCOME), cotton, jujubes, and soybeans (www.intlccs.com/about/products)', = ['coal', 'crude oil', 'fuel oils', 'middle distillates', 'renewables']
# 'Iron ore, aluminium, copper, nickel, manganese (radiant-world.com)', = ['iron ore', 'aluminum', 'copper', 'nickel', 'manganese']
# 'alumina, electrolytic aluminum, coking coal, thermal coal, copper, lead, zinc, rare and precious metals, bauxite, copper concentrate, iron ore (https://www.chalco.com.cn/en/sctxen/cpjyen/)', = ['aluminum', 'coal', 'copper', 'lead', 'zinc', 'precious metals']
# 'manganese ore, manganese alloys, Ferrosilicon, Silicon Metal (OMH 2024 annual report +claude)', = ['manganese', 'silicon']
# 'thermal coal, petroleum products, fuels, transition energy products (google)', = ['thermal coal', 'petroleum', 'fuel oils']
# 'crude oil, feedstocks, refined petroleum products, petrochemicals (google)', = ['crude oil', 'feedstocks', 'petroleum', 'petrochemicals']
# 'Stainless steel plates, stainless steel coils, stainless steel sheets, hot-rolled steel, cold-rolled steel, metals, and metal ores (gemini)'] = ['steel', 'ores']

In [ ]:
commodity_focus_mapping = {
    'Multi-commodity (Oil & Petroleum Products, Natural Gas & LNG, Metals & Minerals, Agri)': ['oil', 'petroleum','natural gas', 'LNG', 'metals', 'soft/agricultural'],
    'Crude Oil, Petroleum Products, LNG, Natural gas, Biogas/BioLNG, thermal coal, metcoke, metals, power/electricity, plastics recycling (company website)':['crude oil','petroleum','LNG', 'natural gas', 'biogas/bioLNG', 'thermal coal', 'metcoke', 'metals', 'power', 'plastics'],
    'Energy, Metals, Agri' : ['energy','metals','soft/agricultural'],
    'Crude oil, refined petroleum products, natural gas and liquefied natural gas, biofuels, power, and carbon emissions.':['crude oil', 'refined petroleum products', 'natural gas', 'LNG', 'biofuels', 'power', 'carbon'],
    'Agri, Soft Commodities, Grains, Oilseeds, coffee, cotton, sugar, rice, juice, food & feed solutions, freight': ['grains','oilseeds', 'coffee','cotton', 'sugar', 'rice', 'juice'],
    'Palm Oil, Sugar, Grains, Oilseeds': ['palm oil', 'sugar', 'grain', 'oilseeds'],
    'Agri, Food, Industrial Raw Materials, cocoa, coffee, cotton, nuts and spices': ['cocoa', 'coffee', 'cottons', 'nuts', 'spices'],
    'Grains, Oilseeds, Sugar, Cotton': ['grains', 'oilseeds', 'sugar', 'cotton'],
    'Grains, Oilseeds, Metals, Energy': ['grains','oilseeds','metals','energy'],
    'Metals, Energy, Agri': ['energy','metals','soft/agricultural'],
    'Grains, Oilseeds, Agri': ['grains','oilseeds'],
    'Grains, Oilseeds, Sugar': ['grains','oilseeds', 'sugar'],
    'Agri, Energy, Metals, Chemicals': ['energy','soft/agricultural','chemicals','metals'],
    'Energy, Metals, Chemicals, Agri': ['energy','soft/agricultural','chemicals','metals'],
    'Crude Oil, LNG, Petroleum Products, Petrochemical & Feedstock, International chartering, Derivatives': ['crude oil', 'LNG', 'petroleum', 'petrochemicals', 'feedstock'],
    'Crude Oil, LNG, Petroleum Products': ['crude oil', 'LNG', 'petroleum'],
    'Crude Oil, Gas, Petroleum Products': ['crude oil', 'LNG', 'petroleum', 'gas'],
    'Crude Oil, LNG, Renewables': ['crude oil', 'LNG', 'renewables'],
    'Energy, Chemicals, Petroleum, Agri': ['petroleum','soft/agricultural','chemicals'],
    'Grains, Pulses, Oilseeds, wheat, sugar, cotton, nuts': ['grains', 'pulses', 'oilseeds', 'wheat', 'sugar', 'cotton', 'nuts'],
    'Palm Oil, Laurics': ['palm oil', 'laurics'],
    'Palm Oil, Oleochemicals': ['palm oil', 'oleochemicals'],
    'Edible Oils, Agri': ['edible oils'],
    'Soybeans, Corn, Wheat, Canola, Barley, Rye, Pulses , Lentils, Non-GMO & Organic grains, etc.': ['soybeans', 'corn', 'wheat', 'canola', 'barley', 'rye', 'pulses', 'lentils', 'grains'],
    'Grains, Feed': ['grains', 'feed'],
     'Agri, Food Ingredients': ['food ingredients'],
    'Grains, Edible Oils, Cotton, Cocoa': ['grains', 'edible oils', 'cotton', 'cocoa'],
     'Sugar': ['sugar'],
    'Soft Commodities': ['soft/agricultural'],
    'Multi-commodity': ['Unknown'],
    'Base Metals, Concentrates' : ['base metals', 'concentrates'],
    'Specialty Metals, Minor Metals': ['specialty metals', 'minor metals'],
    'Metals, Minerals, Concentrates': ['metals', 'minerals', 'concentrates'],
    'Base Metals, non-ferrous ores, concentrates, refined and precious metals and their related by-products': ['base metals', 'non-ferrous metals', 'concetrates', 'refined metals', 'precious metals'],
    'Coal, Minerals, Cement': ['coal', 'minerals', 'cement'],
    'Minerals, Mining, Agri': ['minerals', 'soft/agricultural'],
    'Iron Ore, Coal, Minerals': ['iron ore', 'coal', 'minerals'],
    'Crude, Fuel Oil, Naphtha, LNG, Gasoil, Gasoline': ['crude oil', 'fuel oil', 'naphtha', 'LNG', 'gasoline', 'gasoil'],
    'Petroleum Products, Bunkers, heating oil, fuel oil, middle distillates, crude oil, brent oil ,fuel oil, LPG, Naphtha, Palm oil, Biofuels, Petrochemicals, Gasoline, LNG, Rubber': ['petroleum', 'bunkers', 'heating oil', 'fuel oil', 'distillates', 'crude oil', 'brent oil', 'LPG', 'naphtha', 'palm oil', 'biofuels', 'petrochemicals', 'gasoline', 'rubber'],
    'Petroleum Products': ['petroleum'],
    'Crude Oil, LNG': ['crude oil', 'LNG'],
    'Crude Oil, Petroleum Products': ['crude oil','petroleum'],
    'Petrochemicals, Polymers': ['petrochemicals', 'polymers'],
    'Chemicals, Agri': ['chemicals', 'soft/agricultural'],
    'Chemicals, Solvents': ['chemicals', 'solvents'],
    'Rice, edible oil, sugar, coffee': ['rice', 'edible oil', 'sugar', 'coffee'],
    'Oil Products': ['oil'],
    'LNG, Gas': ['LNG', 'gas'],
    'Energy, Oil Products': ['oil'],
    'Crude Oil, Products': ['crude oil'],
    'Green Commodities, Biofuels': ['biofuels'],
    'Base Metals, precious metals, ferrous metals': ['base metals', 'precious metals', 'ferrous metals'],
    'vegetable oil, renewable fuel, oleochemicals (apicalgroup.com)': ['vegetable oil', 'renewable fuel', 'oleochemicals'],
    'Carbon credits': ['carbon'],
    'Copper, lead, zinc concentrates & refined metals (en.cmoc.com)': ['copper', 'lead', 'zinc', 'refined metals'],
    'Coal, iron ore, copper, aluminum, nickel, lithium, precious metals (mitsubishicorp.com)': ['coal', 'iron ore', 'copper', 'aluminum', 'nickel', 'lithium'],
    'Base metal (Zinc, Lead, Aluminum, Copper, etc), chemical commodity (kztrading.co.kr)': ['zinc', 'lead', 'aluminum', 'copper', 'petrochemicals'],
    'Thermal, coking, and met coal; iron ore, fluxes, and fertilizer raw materials; ferro-alloy products (manganese, silicon, vanadium, titanium); and base materials like nickel and tin, Pulses and beans (pigeon pea, black lentils, green mung beans); feed meals (soya bean meal, rape seed meal); sugar, rice, grains, and other commodities.  (cbonds.com)': ['thermal coal', 'coking coal', 'met coal', 'iron ore', 'fluxes', 'fertilizer raw materials', 'manganese', 'silicon', 'vanadium', 'titanium', 'nickel', 'tin', 'pulses', 'beans', 'feed meals', 'sugar', 'rice', 'grains'],
    'Pulses, Grains, Oilseeds, Rice, Tea and Sugar. Fertilizers and Sulphur,  Thermal Coal, Coking Coal and Petroleum Coke, iron ore, Non-Ferrous( abgtrading.com)': ['pulses', 'grains', 'oilseeds', 'rice', 'tea', 'sugar', 'fertilizers', 'sulphur', 'thermal coal', 'coking coal', 'petroleum coke', 'iron ore', 'non-ferrous metals'],
    'Energy(Natural Gas, LNG, Solar Energy, Wind Energy, Hydrogen, etc.), Steel and Raw Material for Steel, Secondary Battery Materials, Grain, Oils and Fats, Cotton, Bioplastics, Eco-friendly Car Parts (poscointl.com)': ['natural gas', 'LNG', 'solar', 'wind energy', 'hydrogen', 'steel', 'battery materials', 'grain', 'oil', 'fats', 'cotton', 'bioplastics', 'car parts'],
    'sugar, rice, and oil and fat products (https://www.sec.gov/Archives/edgar/data/1949478/000168316826004029/davis_ex9901.htm)': ['sugar', 'rice', 'oil', 'fats'],
    'Coal (https://www.itochu.co.jp/en/business/metal/project/13.html)' : ['coal'],
     'Coal, Fertlizers, Bauxite, Iron Products, Nickel Ore (bary.sg)': ['coal', 'fertilizers', 'bauxite', 'iron', 'nickel ore'],
     'Palm Oil Products (Crude Palm Oil, RBD Palm Olein, and Palm Fatty Acid Distillate) (google ai)': ['palm oil'],
    'Coal & Carbon, Iron & Steel Raw Materials, Battery & Base Metals, Basic Chemicals (Refinery/Cracker Bulk Petrochemicals), Intermediate & Specialty Chemicals, Oils & Fats, Sugar, Dairy & Coffee (Gemini)': ['coal', 'carbon', 'iron', 'steel', 'base metals', 'chemicals', 'oil', 'fats', 'sugar', 'dairy', 'coffee'],
    'Steel, Energy & Resources, Chemicals & Petroleum  (gemini)': ['steel', 'energy', 'chemicals', 'petroleum'],
    'Crude Oi, Petroleum Products, Marine & Biofuels, Aromatics, Polymers (gemini)': ['crude oil', 'petroleum', 'biofuels', 'aromatics', 'polymers'],
    'Mineral Resources (Copper, Nickel, Aluminum, etc.), CPO (Crude Palm Oil) and Refined Palm Oil (oriental-energy.com)': ['copper', 'nickel', 'aluminum', 'palm oil'],
    'crude oil and refined products (naphtha, gasoline, gasoil, jet fuel and fuel oil), asphalt/bitumen, LPG, sulphur and base oil (spc.com.sg)': ['crude oil', 'naphtha', 'gasoline', 'gasoil', 'fuel oil', 'asphalt/bitumen', 'LPG','sulphur', 'base oil'],
    'crude oil, LNG, Refined oil products, chemical products, fuel oil, refining by-products, lubricants, catalysts (sinopecgroup.com)': ['crude oil', 'LNG', 'oil', 'chemicals', 'fuel oil'],
    'Coal, PDEB, EVOH, Rubber additives, White oil, Asphalt (gemini)': ['coal', 'PDEB', 'EVOH', 'rubber additives', 'white oil', 'asphalt'],
    'Marine Fuel oil, gas oil, diesel, motor gasoline, green fuels (gemini)': ['fuel oil', 'gas oil', 'diesel', 'motor gasoline', 'green fuels'],
    'copper, niobium, aluminum, iron ore, and steel, etc (metal.citic)': ['copper', 'niobium', 'aluminum', 'iron ore', 'steel'],
    'Coal, ferrous metals, iron ore, derroalloys, ferrous raw materials, non-ferrous metals, base metals (gemini)': ['coal', 'ferrous metals', 'iron ore', 'ferroalloys', 'non-ferrous metals', 'base metals'],
    'High-grade iron ore, Coking coal, Metallurgical coal, Niobium, Gallium, Neodymium, Light rare earths, Dysprosium, Heavy rare earths, Terbium, Fluorite, Ferrosilicon, Bentonite, Bauxite, Casting coke, Petroleum coke, Iron scrap, Copper, Alumina, Platinum, Palladium, Methanol, Industrial salts, Plastic resins, Biochemicals, Green polyethylene, Biomass resins, Dicyclopentadiene, SBR Latex, ABS Resins, Grains, Wheat, Corn, Animal feed raw materials, Sugar, Coffee beans, Timber, Logs, Woodchips, Plywood, Biomass fuel, Paper products, Chemical fertilizers, Frozen beef, Seafood products, Crude oil, Natural gas, Liquefied Natural Gas, Biomethane, Nuclear fuel (gemini)': ['iron ore', 'coal', 'rare earths', 'minerals', 'metals', 'biochemicals', 'plastics', 'rubber', 'grains', 'feed', 'sugar', 'coffee', 'timber', 'paper', 'fertilizers', 'meat', 'seafood', 'crude oil', 'gas', 'LNG', 'nuclear fuel'],
    'carbon steel, stainless steel, polymers, methanol, organic & inorganic chemicals, fine chemicals, sodium cyanide, mining tires & grinding media, nitrogen fertilizers, compound fertilizers, phosphate fertilizers, non-ferrous metals/concentrates such as copper concentrate, zinc concentrate, precious metal concentrate, non-ferrous metals (refined metal) such as electrolytic copper , etc (trading.samsungcnt.com)': ['steel', 'polymers', 'methanol', 'fertilizers', 'copper', 'zinc', 'ferrous metals', 'precious metals', 'non-ferrous metals'],
    'thermal coal, nickel, bauxite, copper, petrochemicals, steel products, oils, IT components, crude palm oil, oil palm fruits, biofuels (lxinternational.com)': ['thermal coal', 'nickel', 'bauxite', 'copper', 'petrochemicals', 'steel', 'oils', 'palm oil', 'biofuels'],
    'petroleum products, raw materials & semi products, flat steel products, long steel products, Steel Pipes & Tubes, Stainless Steel Products, Polymers (Synthetic Resins), Chemical Fertilizers (hyundaicorp.com)': ['petroleum', 'steel', 'polymers', 'fertilizers'],
    'LNG, crude oil, pipeline natural gas, condensate, LPG, carbon-offset LNG, ammonia & hydrogen (google ai)': ['LNG', 'crude oil', 'natural gas', 'condensate', 'LPG', 'carbon', 'gas'],
    'thermal coal, metallurgical coal (coking coal), third-party coal' : ['coal'],
    'palm oil, sugar cane, rubber, other crops (gemini)': ['palm oil', 'sugar cane', 'rubber'],
    'Chemicals, Energy, Oil and gas (gemini)': ['chemicals', 'gas', 'oil'],
    'Coal (Energy),Ores & Minerals (Industrial Mining): Nickel Ore, Brucite, Bauxite, Iron Products,Fertilizers (Agricultural Chemicals) (gemini)': ['coal', 'ores', 'fertilizers'],
    'Wholesale of metals and metal ores, Wholesale of fuels and related products (gemini)': ['metals', 'ores', 'fuel oils'],
    'Crude Oils, Gasoline, Gasoil, Decant Oil, HVR (High Viscosity Residue), LSCR (Low Sulfur Crude Residue), LSFO (Low Sulfur Fuel Oil), MFO (Marine Fuel Oil), Vacuum Residue, Petrochemicals (pimd.pertamina.com/business-portfolio/)': ['crude oils', 'gasolline', 'gasoil', 'oils', 'petrochemicals'],
    'Palm oil, Palm olein, Palm stearin, Palm kernel oil, Lauric products, Palm kernel cake, Bakery fats, Margarines, Frying oils, Rubber, Biomass, Biogas (gemini)': ['palm oil', 'palm products', 'fats', 'margarines', 'oils', 'rubber', 'biomass', 'biogas'],
    'Angle Bar, Flat Bar, Round Bar, Square Bar, Deformed Bar, Steel Plate, Hollow Section, Channels, Beams/Columns, Pipes, Grating (hgmetal.com)': ['steel'],
    'high-grade iron ore, Coking coal, Metallurgical coal, Niobium, Gallium, Neodymium, Light rare earths, Dysprosium, Heavy rare earths, Terbium, Fluorite, Ferrosilicon, Bentonite, Bauxite, Casting coke, Petroleum coke, Iron scrap, Copper, Alumina, Platinum, Palladium, Methanol, Industrial salts, Plastic resins, Biochemicals, Green polyethylene, Biomass resins, Dicyclopentadiene, SBR Latex, ABS Resins, Grains, Wheat, Corn, Animal feed raw materials, Sugar, Coffee beans, Timber, Logs, Woodchips, Plywood, Biomass fuel, Paper products, Chemical fertilizers, Frozen beef, Seafood products, Crude oil, Natural gas, Liquefied Natural Gas, Biomethane, Nuclear fuel (gemini)': ['iron ore', 'coal', 'rare earths', 'minerals', 'metals', 'petrochemicals', 'biochemicals', 'grains', 'wheat', 'corn', 'sugar', 'coffee', 'timber', 'paper', 'biomass', 'fertilizers', 'meat', 'seafood', 'crude oil', 'natural gas', 'LNG', 'nuclear fuel'],
    'Wheat, Soybeans, Wheat bran, Wheat starch (gemini)': ['wheat', 'soybeans'],
    'crude oil, petroleum products and feedstock (eneos.asia)': ['crude oil', 'petroleum', 'feedstock'],
    'Crude, Gasoline, Naphtha, Middle Distillate, Fuel Oil, Petrochemical, Biodiesel, Carbon Credit  (idemitsu.com)': ['crude oil', 'gasoline', 'naphtha', 'distillates', 'fuel oils', 'petrochemicals', 'biodiesel', 'carbon'],
    'crude oil, petroleum products (cosmo-energy.co.jp)': ['crude oil', 'petroleum'],
    'iron ore, steel trading (jfe-shoji.co.jp)': ['iron ore', 'steel'],
    'thermal coal, coking coal, coke, crude oil, fuel oil, middle distillates, and more, renewable energy such as Brown Grease Methyl Ester (BGME), Used Cooking Oil (UCO), Palm Oil Mill Effluent (POME), Fatty Acid Methyl Ester (FAME), and Used Cooking Oil Methyl Ester (UCOME), cotton, jujubes, and soybeans (www.intlccs.com/about/products)': ['coal', 'crude oil', 'fuel oils', 'middle distillates', 'renewables'],
    'Iron ore, aluminium, copper, nickel, manganese (radiant-world.com)': ['iron ore', 'aluminum', 'copper', 'nickel', 'manganese'],
    'alumina, electrolytic aluminum, coking coal, thermal coal, copper, lead, zinc, rare and precious metals, bauxite, copper concentrate, iron ore (https://www.chalco.com.cn/en/sctxen/cpjyen/)': ['aluminum', 'coal', 'copper', 'lead', 'zinc', 'precious metals'],
    'manganese ore, manganese alloys, Ferrosilicon, Silicon Metal (OMH 2024 annual report +claude)': ['manganese', 'silicon'],
    'thermal coal, petroleum products, fuels, transition energy products (google)': ['thermal coal', 'petroleum', 'fuel oils'],
    'crude oil, feedstocks, refined petroleum products, petrochemicals (google)': ['crude oil', 'feedstocks', 'petroleum', 'petrochemicals'],
    'Stainless steel plates, stainless steel coils, stainless steel sheets, hot-rolled steel, cold-rolled steel, metals, and metal ores (gemini)' : ['steel', 'ores'],
    'Palm Oil': ['palm oil']
}

# Apply mapping only where the original value is a key in the dict.
# Rows not in the dict are left untouched (original value preserved),
# and also collected separately for inspection.
unmapped_rows = []
def apply_commodity_mapping(val):
    if val in commodity_focus_mapping:
        return commodity_focus_mapping[val]
    else:
        unmapped_rows.append(val)
        return val  # leave original untouched
print(unmapped_rows)
p1["Commodity Focus"]  = p1["Commodity Focus"].apply(apply_commodity_mapping)

# turn all list into comma separated string
p1["Commodity Focus"] = p1["Commodity Focus"].apply(
    lambda x: ", ".join(x) if isinstance(x, list) else x
)

p1["Commodity Focus"]

In [ ]:
# clean up 'Legal Name / ACRA UEN
# strip whitespace
p1["Legal Name / ACRA UEN"] = p1["Legal Name / ACRA UEN"].str.strip()
p1["Legal Name / ACRA UEN"].head()

In [ ]:
# strip whitespace from HQ Country, remove brackets and lowercase
p1["HQ Country"].unique()
p1["HQ Country"] = p1["HQ Country"].str.replace(r"\(.*?\)", "", regex=True).str.strip()
HQ_mapping = {
    "Geneva, Switzerland": "Switzerland",
    "Bombay House in Mumbai, India.": "India",
    "Tokyo,Osaka": "Japan",
    "Seoul, South Korea.": "South Korea",
    "Singapore , parent in Japan": "Singapore, Japan",
    "London, England": "UK",
    "Tokyo, Japan": "Japan",
    "Petaling Jaya, Selangor": "Malaysia",
    "United Kingdom": "UK",
    "Singapore, global hq: Hong Kong": "Singapore, Hong Kong",
    "Hong Kong , Singapore": "Singapore, Hong Kong",
    "United States": "USA",
    "London, UK": "UK",
    "Mumbai, India.": "India",
    "Seoul, South Korea": "South Korea",
    "Beijing, China.": "China",
    "Republic of Singapore": "Singapore",
    "Jakarta, Indonesia": "Indonesia",
    "Nagoya, Japan": "Japan",
    "Singapore; UK": "Singapore, UK",
    "Singapore; India": "Singapore, India",
    "Singapore , Switzerland": "Singapore, Switzerland",
    "Korea": "South Korea",
    "Dubai, UAE": "UAE",  
    "Dubai": "UAE",
}

p1["HQ Country"] = p1["HQ Country"].replace(HQ_mapping)
p1["HQ Country"].unique()
p1["HQ Country"][:10]

In [ ]:
# check apac offices
#trim whitespace
p1["APAC Offices"] = p1["APAC Offices"].str.strip()
p1['APAC Offices']

In [ ]:
# check Estimated Revenue
# strip whitespace & lowercase
p1["Estimated Revenue"] = p1["Estimated Revenue"].str.strip()

#cannot use revenue to size the nodes because the revenue are inaccurate: inconsistent years, inaccurate number, some are ranges, 
# some are turnover / net sales / total sales / net brokerage
#some number is at group level or consolidated, some is quarterly figure or half of the year figure
#leave it as it is with no more standardizaton

In [ ]:
# check headcount(estimated numbers with inconsistent year, some belong to group, some belong to SG branch, some are ranges)
# remove the word 'employees'
p1["Headcount (Global)"] = p1["Headcount (Global)"].str.replace(r"employees?", "", case=False, regex=True)
# remove whitespace
p1["Headcount (Global)"] = p1["Headcount (Global)"].str.strip()
p1["Headcount (Global)"]

In [ ]:
# check trade volume (inaccurate), estimated numbers, inconsistent year, some are total trade volume some are just across a few commodity types, most cases are undisclosed
# some are ranges
# remove whitespace
p1["Trade Volume (Est.)"] = p1["Trade Volume (Est.)"].str.strip()
p1["Trade Volume (Est.)"]

In [ ]:
# check ownership structure
# remove brackets & whitespace & make it lowercase
p1["Ownership Structure"] = p1["Ownership Structure"].str.replace(r'\(.*?\)', '', regex=True).str.strip().str.lower()
p1["Ownership Structure"] = (
    p1["Ownership Structure"]
    .str.replace(
        r"listed, ultimate parent company is state-owned)",
        "listed, ultimate parent company is state-owned",
        regex=False,
    )
    .str.strip()
    .str.lower()
)

p1["Ownership Structure"].unique()

In [ ]:
# check Listed / Exchange
# remove brackets & whitespace
p1["Exchange"] = p1["Exchange"].str.strip()

# pattern to find inside each cell, its canoncial name / transformation. Format as list of tuples [(,),(,),(,)...] where (,) has (pattern, cannonical)
# \b*\b is word boundary. Ex: \bLSE\b will extract only LSE and not PULSE.
standardized_exchange = [
    (r"\blse\b|london", "London Stock Exchange LSE"),
    (r"\bnyse\b|new york", "New York Stock Exchange NYSE"),
    (r"\btse\b|tokyo", "Tokyo Stock Exchange TSE"),
    (r"\bset\b|thailand", "The Stock Exchange of Thailand SET"),
    (r"\bams\b|amsterdam", "Euronext Amsterdam AMS"),
    (r"\bparis\b", "Euronext Paris ENX"),
    (r"\bsgx\b|singapore", "Singapore Exchange SGX"),
    (r"\bhkex\b|hong kong", "Stock Exchange of Hong Kong HKEX"),
    (r"\bkrx\b|korea", "Korea Exchange KRX"),
    (r"\bnasdaq\b", "Nasdaq Stock Market NDAQ"),
    (r"\basx\b|australian securities", "Australian Securities Exchange ASX"),
    (r"\bidx\b|indonesia", "Indonesia Stock Exchange IDX"),
    (r"\bmyx\b|malaysia", "Malaysia Exchange MYX"),
    (r"\bsse\b|shanghai", "Shanghai Stock Exchange SSE"),
]

def standardize(text):
    #check if the cell is na or empty str or unknown
    if pd.isna(text) or text.strip() == '' or 'unknown' in text.lower():
        #return it 
        return text
    else:
        text = text.lower() #put here so capitalized 'Unknown' doesn't become lowercase
        #list to store unique exchange 
        found = []
        #text has exchange, find the pattern in the text
        for pattern, cannonical in standardized_exchange:
            if re.search(pattern, text, re.IGNORECASE): #returns true of pattern is found in text
                if cannonical not in found: #avoids duplication of the same cannonical if pattern is found once
                    found.append(cannonical)
    #once all patterns are found, join the cannonicals as a string and return else return original text if patterns were not found
    return ', '.join(found) if found else text

# run this function for every row in the exchange column
p1['Exchange'] = p1['Exchange'].apply(standardize)
p1["Exchange"].unique()

In [ ]:
#check notes
#remove whitespace
p1['Notes'] = p1['Notes'].str.strip()

In [ ]:
p1.head()

In [ ]:
# reset all index again
p1 = p1.reset_index(drop=True)
p1

In [ ]:
# save as cleaned_pillar1
p1.to_csv(r"D:\commo\code\cleaned_pillars\cleaned_pillar1.csv", index=False)